const regularAlumni = [
{ name: 'Aarya Hire', department: 'Computer Science and Engineering (AI-ML)', year: '2025', photo: 'images/default-avatar.jpg', description: "Masters of Global Business (2025–2027), S P Jain School of Global Management" },
{ name: 'Dhanashree Suresh Yadav', department: 'Computer Science and Engineering (AI-ML)', year: '2025', photo: 'images/default-avatar.jpg', description: "M.Tech in Data Science (2025–2027), COEP Technological University, Pune" },
{ name: 'Siddhesh Pohare', department: 'Computer Science and Engineering (AI-ML)', year: '2026', photo: 'images/default-avatar.jpg', description: 'TY B.Tech Student' },
{ name: 'Chetan Harshad Indulkar', department: 'Computer Science and Engineering (AI-ML)', year: '2025', photo: 'images/default-avatar.jpg', description: 'Final Year B.Tech Student' },
{ name: 'Dharin Dave', department: 'Computer Science and Engineering (AI-ML)', year: '2025', photo: 'images/default-avatar.jpg', description: 'Final Year B.Tech Student' },
{ name: 'Soham Devidas Mhatre', department: 'Computer Science and Engineering (AI-ML)', year: '2026', photo: 'images/default-avatar.jpg', description: 'TY B.Tech Student' },
{ name: 'Sushant Kabra', department: 'Computer Science and Engineering (AI-ML)', year: '2026', photo: 'images/default-avatar.jpg', description: 'TY B.Tech Student' },
{ name: 'Dhanashree Yadav', department: 'Computer Science and Engineering (AI-ML)', year: '2025', photo: 'images/default-avatar.jpg', description: 'Final Year B.Tech Student' },
{ name: 'Siddharth Ashok Balai', department: 'Computer Science and Engineering (AI-ML)', year: '2026', photo: 'images/default-avatar.jpg', description: 'TY B.Tech Student' },
{ name: 'Samiksha Dhurve', department: 'Computer Science and Engineering (AI-ML)', year: '2026', photo: 'images/default-avatar.jpg', description: 'TY B.Tech Student' },
{ name: 'Ayush Dongardive', department: 'Computer Science and Engineering (AI-ML)', year: '2025', photo: 'images/default-avatar.jpg', description: 'Final Year B.Tech Student' },
{ name: 'Harshad Arun Gholve', department: 'Computer Science and Engineering (AI-ML)', year: '2025', photo: 'images/default-avatar.jpg', description: 'Final Year B.Tech Student' },
{ name: 'Jivan Santosh Karande', department: 'Computer Science and Engineering (AI-ML)', year: '2025', photo: 'images/default-avatar.jpg', description: 'Final Year B.Tech Student' },
{ name: 'Gaurav Tarate', department: 'Computer Science and Engineering (AI-ML)', year: '2026', photo: 'images/default-avatar.jpg', description: 'TY B.Tech Student' },
{ name: 'Sana Sampson', department: 'Computer Science and Engineering (AI-ML)', year: '2025', photo: 'images/default-avatar.jpg', description: 'Final Year B.Tech Student' },
{ name: 'Suyash Sanjay Gadhave', department: 'Computer Science and Engineering (AI-ML)', year: '2025', photo: 'images/default-avatar.jpg', description: 'Final Year B.Tech Student' },
{ name: 'Aryan Agarkar', department: 'Computer Science and Engineering (AI-ML)', year: '2026', photo: 'images/default-avatar.jpg', description: 'TY B.Tech Student' },
{ name: 'Prathmesh Kolekar', department: 'Computer Science and Engineering (AI-ML)', year: '2025', photo: 'images/default-avatar.jpg', description: 'Final Year B.Tech Student' },
{ name: 'Om Gunesh Satturwar', department: 'Computer Science and Engineering (AI-ML)', year: '2025', photo: 'images/default-avatar.jpg', description: 'Final Year B.Tech Student' },
{ name: 'Prathamesh Dikholkar', department: 'Computer Science and Engineering (AI-ML)', year: '2026', photo: 'images/default-avatar.jpg', description: 'TY B.Tech Student' },
{ name: 'Vaishnavi Gajanan Chopade', department: 'Computer Science and Engineering (AI-ML)', year: '2025', photo: 'images/default-avatar.jpg', description: 'Final Year B.Tech Student' },
{ name: 'Harshraj Singh Chouhan', department: 'Computer Science and Engineering (AI-ML)', year: '2025', photo: 'images/default-avatar.jpg', description: 'Final Year B.Tech Student' },
{ name: 'Abhishek Bichare', department: 'Computer Science and Engineering (AI-ML)', year: '2026', photo: 'images/default-avatar.jpg', description: 'TY B.Tech Student' },
{ name: 'Soham Tukaram Narsale', department: 'Computer Science and Engineering (AI-ML)', year: '2025', photo: 'images/default-avatar.jpg', description: 'Final Year B.Tech Student' },
{ name: 'Pranav Ukhade', department: 'Computer Science and Engineering (AI-ML)', year: '2026', photo: 'images/default-avatar.jpg', description: 'TY B.Tech Student' },
{ name: 'Namish Arora', department: 'Computer Science and Engineering (AI-ML)', year: '2026', photo: 'images/default-avatar.jpg', description: 'TY B.Tech Student' },
{ name: 'Yash Sonar', department: 'Computer Science and Engineering (AI-ML)', year: '2025', photo: 'images/default-avatar.jpg', description: 'Final Year B.Tech Student' },

{ name: 'Gaurav Mahale', department: 'Computer Engineering REGIONAL', year: '2025', photo: 'images/default-avatar.jpg', description: 'MS in Data Science (2025–26, Pursuing), University of Glasgow, UK' },

{ name: 'Anandkumar Birajdar', department: 'Information Technology Engineering', year: '2006', photo: 'images/default-avatar.jpg', description: 'Assistant Professor, PCCOE' },
{ name: 'Ajinkya Waghulde', department: 'Information Technology Engineering', year: '2009', photo: 'images/default-avatar.jpg', description: 'MS CS - Game Development (2011-2013), University of Southern California' },
{ name: 'Ninad Oak', department: 'Information Technology Engineering', year: '2011', photo: 'images/default-avatar.jpg', description: 'University of Pennsylvania, US' },
{ name: 'Tejas Sanjay Desale', department: 'Information Technology Engineering', year: '2014', photo: 'images/default-avatar.jpg', description: 'Central Institute of Road Transport' },
{ name: 'Sagar Deshmukh', department: 'Information Technology Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'MBA, D Y Patil PGDM Institute, Assistant Professor, Pune Business School' },
{ name: 'Abhijit Pawar', department: 'Information Technology Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: '' },
{ name: 'Raksha Kate', department: 'Information Technology Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: '' },
{ name: 'Rhuta Joshi', department: 'Information Technology Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MSE in Computer Graphics and Gaming (2021-2023)' },
{ name: 'Shivani Birajdar', department: 'Information Technology Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MS Human Computer Interaction (2022-2023), University of California' },
{ name: 'Shambhavi Mokadam', department: 'Information Technology Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'MS Information System Management (2025), Carnegie Mellon University, US' },
{ name: 'Yash Bhirud', department: 'Information Technology Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: '' },
{ name: 'Aditya Padgal', department: 'Information Technology Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'MS (2024-2025), Indiana University, US' },
{ name: 'Atharva Vijay Jadhav', department: 'Information Technology Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'MS (2023), RWTH Aachen University, Germany' },
{ name: 'Yash Joshi', department: 'Information Technology Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'MSc Media Informatics (2021-2024), RWTH Aachen, Germany' },
{ name: 'Bhushan Mohol', department: 'Information Technology Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS in AI, National University of Singapore' },
{ name: 'Nupoor Kulkarni', department: 'Information Technology Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS CS (Oct 2023 - Sept 2025), Saarland University, Germany' },
{ name: 'Abhishek Bharne', department: 'Information Technology Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MBA' },
{ name: 'Shaunak Tripathi', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS (2024), Illinois Institute of Technology, Chicago, US' },
{ name: 'Sakshi Pawar', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS (2024), Universities of Texas, US' },
{ name: 'Deep Ramdave', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MBA (2023-2025), IIT Delhi, India' },
{ name: 'Shivam Desale', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS (2024), San Diego State University, California, US' },
{ name: 'Mihir Amode', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MBA (2024-2025), SIES College of Management Studies, Mumbai, India' },
{ name: 'Ajinkya Dhainje', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS CS, University of Warwick, UK' },
{ name: 'Mandar Rao', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS Cyber Security (2024-2025), University of Washington Bothell, US' },
{ name: 'Jainam Jain', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS, University of Buffalo, US' },
{ name: 'Mohammad Abdul Mughni', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS AI (2024-2025), Anglia Ruskin University, UK' },
{ name: 'Darshan Phaldesai', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS Computer Software Engineering (2025-2026), Arizona State University, US' },
{ name: 'Karan Kavatage', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS CS (2025-2026), California State University, US' },
{ name: 'Shantanu Zadbuke', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS SE, San Jose State University, US' },
{ name: 'Divya Rajput', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS CS, University of Southern California, US' },
{ name: 'Shakyadeep Khobragade', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MBA (2023-2025)' },
{ name: 'Devika Nikam', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS (2023-2024), UK' },
{ name: 'Janhavi Dhajekar', department: 'Information Technology Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2024)' },
{ name: 'Shreyas Wetal', department: 'Information Technology Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2024), University of Sydney, Australia' },
{ name: 'Yash Tembhurnikar', department: 'Information Technology Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2025), Purdue University' },
{ name: 'Pratiksha Kashid', department: 'Information Technology Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2025), UNSW Sydney' },
{ name: 'Divyank Panwar', department: 'Information Technology Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (2025-26, Pursuing), IIT Kanpur' },
{ name: 'Pooja Nemade', department: 'Information Technology Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MS (2025-26, Pursuing), Buffalo University' },
{ name: 'Trisha Navani', department: 'Information Technology Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (2025-26, Pursuing), PCCOE' },

{ name: 'Prathamesh Bacchav', department: 'Computer Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MBA (2025)' },
{ name: 'Sarthak Phulari', department: 'Computer Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (2025)' },
{ name: 'Makardhwaj Kamble', department: 'Computer Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (2025)' },
{ name: 'Ankita Anarase', department: 'Computer Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MS (2025)' },
{ name: 'Pranav Patil', department: 'Computer Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (2025)' },
{ name: 'Hardik Jain', department: 'Computer Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech (2024)' },
{ name: 'Kuldeep Lakhe', department: 'Computer Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech (2024)' },
{ name: 'Saee Chormunge', department: 'Computer Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech (2024)' },
{ name: 'Sharvari Kale', department: 'Computer Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2024)' },
{ name: 'Apeksha Mulimani', department: 'Computer Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2024)' },
{ name: 'Bhagyesha Patil', department: 'Computer Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2024)' },
{ name: 'Pratik Patik', department: 'Computer Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2024)' },
{ name: 'Mohit Gandhi', department: 'Computer Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS' },
{ name: 'Ashish Kulkarni', department: 'Computer Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'M.Tech' },
{ name: 'Sakshi Kshirsagar', department: 'Computer Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS' },
{ name: 'Niraj Sawant', department: 'Computer Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS' },
{ name: 'Vishal Pange', department: 'Computer Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS' },
{ name: 'Sumedh Joshi', department: 'Computer Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS' },
{ name: 'Yash Vibhute', department: 'Computer Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS' },

{ name: 'Anil Katte', department: 'Mechanical Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (Computational Mechanics), PCCoE, India' },
{ name: 'Pradnya Bhapkar', department: 'Mechanical Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (Computational Mechanics), PCCoE, India' },
{ name: 'Chaitanya Kulkarni', department: 'Mechanical Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (Aerospace Engineering), DIAT-DRDO, India' },
{ name: 'Parth Deshmukh', department: 'Mechanical Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (Mechanical Engineering), DIAT-DRDO, India' },
{ name: 'Aditya Kotwal', department: 'Mechanical Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (Thermal Engineering), IIT-Delhi, India' },
{ name: 'Ninad Acharya', department: 'Mechanical Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (Manufacturing Engineering), NIT-Warangal, India' },
{ name: 'MIHIR AMIT BHANSALI', department: 'Mechanical Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS Appl. Data Science, University of Florida, Florida' },
{ name: 'INGALE AVANTI SADASHIV', department: 'Mechanical Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MBA, DY Patil University Pune, India' },
{ name: 'SIDDHARTH DNYANESHWAR BANDAWANE', department: 'Mechanical Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'UG Researcher, University of Wisconsin-Madison' },
{ name: 'DAIVIK CHANDRABHAN BAVISKAR', department: 'Mechanical Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'Indian Maritime University Mumbai, India' },
{ name: 'DAMDHAR KAUSTUBH DEVIDAS', department: 'Mechanical Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'University of Mumbai, India' },
{ name: 'GOVIND MANOJKUMAR BAGDIYA', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'PGD-ERP, COEP, India' },
{ name: 'NISHIGANDHA GANESH DAREKAR', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS, Technische Universität Berlin, Germany' },
{ name: 'VARUN SHRIRAM GAWADE', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MIM, ESSEC Business School, France' },
{ name: 'VAISHNAV RAVINDRA KALDATE', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MEng, University of Massachusetts Amherst, USA' },
{ name: 'AKASH RAJESH MORE', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'PGDM, ISBS, Pune' },
{ name: 'SANKET RAJESH NAMPURKAR', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MSc, University of Manchester, England' },
{ name: 'TANISHQ VIJAYKUMAR PATIL', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "Master's" },
{ name: 'WAKE ADITYA SUNIL', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "Master's" },
{ name: 'ROHAN RAVINDRA KHARAT', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech, COEP, Pune' },
{ name: 'ADWAIT DEEPAK KULKARNI', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS in Robotics, Boston University, United States' },
{ name: 'ANUJA SUNIL RUPNAR', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS in Mech, Worcester Polytechnic Institute, Worcester, Massachusetts' },
{ name: 'OM VITTHALRAO SANGLE', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS in Mech and Process Engg., TU Bergakademie Freiberg, Germany' },
{ name: 'SONIYA RAMESH SHAH', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS in Engg. Mgt, Texas A&M University, United States' },
{ name: 'ROHIT RAJESH PAWAR', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'Master Degree, Aston University, England' },
{ name: 'ANIKET WAMAN DIDARE', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS in Science, Indian Institute of Technology, India' },
{ name: 'SHREEDHAR VIJAY LOHAR', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech in Mechatronics, COEP Technological University, India' },
{ name: 'NIMISH NITIN MAHADAR', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS, Arizona State University' },
{ name: 'JESWIN GIGI MATHEW', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'Master in Mech Engg., Technological University Dublin, Ireland' },
{ name: 'RAMAYANE SAURABH DEEPAK', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MBA, DY Patil Institute of Distance Learning, India' },
{ name: 'AAMOD VINAYAK PANDE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'ME in Robotics, Mechatronics and Automation, RMIT, Australia' },
{ name: 'AMEY RAVINDRA THONGE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'ME in Automotive Engineering, Technische Hochschule Ingolstadt, Germany' },
{ name: 'CHAITANYA DIGAMBAR KSHIRSAGAR', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Big Data Analytics, SunBeam Institute of Information Technology, India' },
{ name: 'TEJAS GULABRAO CHAVAN', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MBA in HRM & Services, SPPU, India' },
{ name: 'NACHIKET SAGAR DESHPANDE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'ME in Industrial Management, University of South California / USC Marshall School of Business, USA' },
{ name: 'PRAJWAL TRYAMBAKRAO DHOTE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MBA, K J Somaiya, India' },
{ name: 'PIYUSH JITESH GONAL', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Masters in Forecast and Technology Management, Technische Hochschule Ingolstadt, Germany' },
{ name: 'SAURABH MAHESH JADHAV', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Masters in Automotive Engineering, Technische Hochschule Ingolstadt, Germany' },
{ name: 'MALHAR RAHUL KHOLE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MTech Material Science and Technology, IIT Varanasi, India' },
{ name: 'MEHUL VINAYAK MANE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MTech in Designing, MIT-WPU, India' },
{ name: 'AKASH GIRISH GUGGARI', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'M.E. in Logistics, Materials and Supply Chains, Berlin School of Business & Innovation (BSBI), Germany' },
{ name: 'HARSHAL HARISCHANDRA MEHER', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MBA, IIM Lucknow, India' },
{ name: 'UMESH RAJSHEKHAR NANDARGI', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'ME Automotive System, Hochschule Esslingen - University of Applied Sciences, Germany' },
{ name: 'ATHARV RAJESH NIRHALI', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'ME Industrial Engineering, Northeastern University, USA' },
{ name: 'OJAS JAIPRAKASH VISHWAKARMA', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'M.S. Renewable Energy System, Hamburg University of Applied Sciences, Germany' },
{ name: 'PRANITA UMESH PACHKAWADE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS Sustainable Energy System, University of Freiburg, Germany' },
{ name: 'AKANKSHA PRAKASH PAWAR', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS Engineering and Management, Technische Hochschule Ingolstadt, Germany' },
{ name: 'TUSHAR BADRINATH RANE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MBA Operations Management and Supervision, NMIMS CDOE, India' },
{ name: 'RUTURAJ PRASHANT YAWALE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'ME International Automotive Engineering, Technische Hochschule Ingolstadt, Germany' },
{ name: 'SAKSHI GANESH SHENDE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS in Mechanical Engineering, New York University, USA' },
{ name: 'SAURABH SURYAKANT NAGENDRA', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MTech in Computer Integrated Manufacturing, NIT Warangal, India' },
{ name: 'HRISHIKESH SUHAS SHINTRE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Business Administration (General), Sydenham Institute of Management Studies, India' },
{ name: 'SHREYASH SHRIKANT KULKARNI', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Masters in Logistics Management and Supply Chain, University of Warwick, England' },
{ name: 'PRANAV TUKARAM TATHE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MBA, IIM Calcutta, India' },
{ name: 'DIGVIJAY CHANDRASEN THAKARE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Machine Design, IIT Guwahati, India' },
{ name: 'PRAJWAL VIJAY THORAT', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Electric Vehicles, MIT ADT, India' },
{ name: 'URVESH VIKHIAT BERRY', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Business Management, London Business School, England' },
{ name: 'TANMAY RAJESH VINCHAVEKAR', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Management Studies, Jamnalal Institute of Management Studies, India' },
{ name: 'RUGVED SHARADRAO WANKHADE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Marketing Management, Indira School of Business Studies PGDM, India' },
{ name: 'PRATHAMESH PRALHAD PAWAR', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Management, IIT Kanpur, India' },
{ name: 'NIKHIL CHHOTU SOMWANSHI', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Management & Business Analytics, IISc, India' },
{ name: 'RANBIRSINGH MANMITSINGH SAINI', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Engineering Management, University of Leicester, England' },
{ name: 'ADITYA PRAMOD PALANDE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Industrial Engineering, Penn State University, United States' },
{ name: 'ADITYA RAVI JADHAV', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Management, ESCP Business School, Germany/Spain' },
{ name: 'ATHARVA AJAY DESHPANDE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Mechanical Engineering, New York University, United States' },
{ name: 'PRATIK JANARDAN AVHAD', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Mechanical Engineering, Pimpri Chinchwad College of Engineering, India' },
{ name: 'ATHARVA RAVINDRA BHORPE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Mechatronics, Robotics and Automation, RWTH Aachen University, Germany' },
{ name: 'PRANAV PRADIP CHANDUGADE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Supply Chain Management, SRH University, Germany' },
{ name: 'SOHAM SHRISH KHARKAR', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Computer Aided Mechanical Engineering, RWTH Aachen University, Germany' },
{ name: 'PRANAV PRASHANT DAHIWADE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Management, Frankfurt School of Finance and Management, Germany' },
{ name: 'ANJALI SANJAY RAUT', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Supply Chain and Logistics Management, University of Warwick, England' },
{ name: 'SIDDHARTH VINAYAK SHROTRI', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Mechatronics, Automation and Robotics, Worcester Polytechnic Institute, USA' },
{ name: 'SUVID SANJAY SHINDE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Robotic Systems Engineer, RWTH Aachen University, Germany' },
{ name: 'AMEY PRAVIN TALEGAONKAR', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Management, Imperial College Business School, England' },
{ name: 'VAISHNAVI BHALCHANDRA KASAR', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Industrial Engineering, North Carolina State University, United States' },
{ name: 'HRITIKA SANJAY WAGHJALE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Industrial Engineering, Penn State University, United States' },
{ name: 'GANESH ABHAY BHARAMBE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Business Administration, Department of Management Science (PUMBA), India' },

{ name: 'Miss. Vijaya Ghatol', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MBA in Sustainable Energy Management (2025–26), NICMAR, Pune, India' },
{ name: 'Ganesh Kodnani', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MBA in Advanced Construction Management (2025–26), NICMAR, Pune, India' },
{ name: 'Manas Tendulkar', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MBA in Advanced Construction Management (2025–26), NICMAR, Pune, India' },
{ name: 'Tejas Solunke', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MBA in Advanced Construction Management (2025–26), NICMAR, Pune, India' },
{ name: 'Gurkiratsingh Arora', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MTech in Computer Aided Structural Engineering (2025–26), IIIT Hyderabad, India' },
{ name: 'Devesh Patil', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MSc in Construction Management (2025–26), University of Birmingham, Dubai' },
{ name: 'Vaishnavi Patil', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MTech in Town Planning (2025–26), COEP Technical University, Pune, India' },
{ name: 'Onkar Kusmade', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MTech in Structures (2025–26), IIT Madras, India' },
{ name: 'Varun Desai', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MS in Building Construction and Facilities Management (2025–26), Georgia Tech, Atlanta' },
{ name: 'Aditya Tatiya', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MS in Master of Business Analytics (2025–26), University of Technology Sydney' },
{ name: 'Tanmay Bhalerao', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech in Structural Engineering (2024–25), IIT Bombay, India' },
{ name: 'Shruti Jadhav', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS in Construction Management (2024–25), Arizona State University, USA' },
{ name: 'Rohit Shinde', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech in Environmental Engineering (2024–25), NIT Trichy, India' },
{ name: 'Pooja More', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS in Structural Engineering (2024–25), University of Illinois Urbana-Champaign, USA' },
{ name: 'Sanket Pawar', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MBA in Construction Project Management (2024–25), NICMAR, Pune, India' },
{ name: 'Neha Patil', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech in Geotechnical Engineering (2024–25), IIT Delhi, India' },
{ name: 'Akshay Kulkarni', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS in Transportation Engineering (2024–25), Purdue University, USA' },
{ name: 'Rutuja Deshmukh', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech in Water Resources Engineering (2024–25), IIT Roorkee, India' },
{ name: 'Prasad Chavan', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS in Construction Engineering and Management (2024–25), University of Michigan, USA' },
{ name: 'Amit Desai', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'M.Tech in Structural Engineering (2022–23), IIT Madras, India' },
{ name: 'Kiran Patil', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS in Construction Management (2022–23), Texas A&M University, USA' },
{ name: 'Sneha Kulkarni', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'M.Tech in Environmental Engineering (2022–23), IIT Kanpur, India' },
{ name: 'Rohit Jagtap', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS in Structural Engineering (2022–23), University of Texas at Austin, USA' },
{ name: 'Pallavi Shinde', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MBA in Infrastructure Management (2022–23), NICMAR, Pune, India' },
{ name: 'Sagar More', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'M.Tech in Geotechnical Engineering (2023–24), IIT Bombay, India' },
{ name: 'Vaishnavi Pawar', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS in Construction Engineering (2023–24), Arizona State University, USA' },
{ name: 'Harshal Patil', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'M.Tech in Transportation Engineering (2023–24), NIT Warangal, India' },
{ name: 'Rutuja Kale', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS in Environmental Engineering (2023–24), University of California Davis, USA' },
{ name: 'Omkar Jadhav', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MBA in Construction Project Management (2023–24), RICS School of Built Environment, India' },
{ name: 'Tanmay Bhalerao', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech in Structural Engineering (2024–25), IIT Bombay, India' },
{ name: 'Shruti Jadhav', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS in Construction Management (2024–25), Arizona State University, USA' },
{ name: 'Rohit Shinde', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech in Environmental Engineering (2024–25), NIT Trichy, India' },
{ name: 'Pooja More', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS in Structural Engineering (2024–25), University of Illinois Urbana-Champaign, USA' },
{ name: 'Sanket Pawar', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MBA in Construction Project Management (2024–25), NICMAR, Pune, India' },
{ name: 'Neha Patil', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech in Geotechnical Engineering (2024–25), IIT Delhi, India' },
{ name: 'Akshay Kulkarni', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS in Transportation Engineering (2024–25), Purdue University, USA' },
{ name: 'Rutuja Deshmukh', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech in Water Resources Engineering (2024–25), IIT Roorkee, India' },
{ name: 'Prasad Chavan', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS in Construction Engineering and Management (2024–25), University of Michigan, USA' },
{ name: 'Aditya Kulkarni', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech in Structural Engineering (2025–26), IIT Hyderabad, India' },
{ name: 'Sakshi Deshmukh', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MS in Environmental Engineering (2025–26), University of Texas at Dallas, USA' },
{ name: 'Nikhil Patil', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech in Construction Technology (2025–26), IIT Guwahati, India' },
{ name: 'Aishwarya More', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MS in Transportation Engineering (2025–26), University of Florida, USA' },
{ name: 'Rahul Shinde', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MBA in Infrastructure Management (2025–26), NICMAR, Pune, India' },

{ name: 'Arin Ashish Jain', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech Micro Electronics and VLSI Design (2025-2027), National Institute of Technology Calicut, India' },
{ name: 'Shreya Rajendra Desai', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.S. in Embedded System, Chemnitz Technical University, Germany' },
{ name: 'Janhavi Chati', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MSc Electronics Engineering, University of Southampton, England' },
{ name: 'Pradnya Rajendra Deore', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MBA General Management (2025-2027), Indian Institute of Management Visakhapatnam, India' },
{ name: 'Mohammad Bohra', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech Micro Electronics and VLSI Design (Solid State Devices) (2025-2027), IIT Bombay, India' },
{ name: 'Onkar Tukaram Bobade', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech Microelectronics and VLSI (2026-2028), IIT Hyderabad, India' },
{ name: 'Soumitya Sanjay Patil', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS Infotech (Embedded Systems) (2026-2028), University of Stuttgart, Germany' },
{ name: 'Nilkanth Kadlag', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "Master’s of Science Computer Science (August 2023 - July 2025), University of Georgia, United States of America" },
{ name: 'Sandeep Sharma', department: 'Electronics and Telecommunication Engineering', year: '2008', photo: 'images/default-avatar.jpg', description: "MS ECE (Electrical and Computer Engineering), Missouri University of Science and Technology" },
{ name: 'Jaydeep Ananda Mohite', department: 'Electronics and Telecommunication Engineering', year: '2010', photo: 'images/default-avatar.jpg', description: "M.Tech Electronics Engineering, Walchand College of Engineering Sangli" },
{ name: 'Dr. Mane Harshali Dnyaneshwar', department: 'Electronics and Telecommunication Engineering', year: '2011', photo: 'images/default-avatar.jpg', description: "PhD Signal Processing, K L University" },
{ name: 'Jaywant Kamble', department: 'Electronics and Telecommunication Engineering', year: '2013', photo: 'images/default-avatar.jpg', description: "ME VLSI and Embedded Systems, Pune University" },
{ name: 'Sailee Borse', department: 'Electronics and Telecommunication Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: "MBA General, Indian Institute of Management Kozhikode" },
{ name: 'Shreekanya Kodate', department: 'Electronics and Telecommunication Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: "M.Tech Communication Engineering, Indian Institute of Technology Bombay" },
{ name: 'Shalvraj Dhananjay Kulkarni', department: 'Electronics and Telecommunication Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: "M.Tech Automotive Electronics, VIT Vellore (University Gold Medalist)" },
{ name: 'Siddhi Gaikwad', department: 'Electronics and Telecommunication Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: "M.Sc. Electronic Information Engineering, Trinity College Dublin" },
{ name: 'Mahesh Balasaheb Raut', department: 'Electronics and Telecommunication Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: "Masters Data Science, University of Guelph" },
{ name: 'Antara Deepak Muley', department: 'Electronics and Telecommunication Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: "MS Electrical and Computer Engineering, Michigan Technological University" },
{ name: 'Harshit Sampgaon', department: 'Electronics and Telecommunication Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: "MS Electrical and Computer Engineering - Machine Learning, Northeastern University" },
{ name: 'Snehal Patil', department: 'Electronics and Telecommunication Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: "MS Electrical Engineering, California State University Fullerton" },
{ name: 'Gaurree Lohiya', department: 'Electronics and Telecommunication Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: "MS Engineering Management, University of Illinois at Urbana Champaign" },
{ name: 'Nikhil Samir Bhosale', department: 'Electronics and Telecommunication Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: "MS Data Science and Analytics, Illinois Institute of Technology" },
{ name: 'Raviraj Mahadeo Khopade', department: 'Electronics and Telecommunication Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: "MS Computer Science, Illinois Institute of Technology" },
{ name: 'Aniket Chopade', department: 'Electronics and Telecommunication Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: "MS Computer Engineering, San Jose State University" },
{ name: 'Akash Rajesh Biyani', department: 'Electronics and Telecommunication Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: "MSc Embedded Computing System, University of Southampton & RPTU Kaiserslautern" },
{ name: 'Shounak Rajendra Powar', department: 'Electronics and Telecommunication Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: "MS Computer Science, Iowa State University" },
{ name: 'Shashank Tiwari', department: 'Electronics and Telecommunication Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: "MBA Human Resource Management, XLRI Jamshedpur" },
{ name: 'Utkarsha Vikas Chinchore', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "MS Mechatronics, KTH Royal Institute of Technology Sweden" },
{ name: 'Jaiee Anand Bhange', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "Master of Information Technology - Artificial Intelligence, University of New South Wales Sydney" },
{ name: 'Chirag Ramesh Kharche', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "MS Electrical Engineering - Power Electronics, Virginia Tech" },
{ name: 'Tushar Subhash Alase', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "MS Electrical & Computer Engineering, Purdue University" },
{ name: 'Shubham Rajesh Kumar Das', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "Ph.D. Theoretical Physics, The Institute of Mathematical Sciences (IMSc)" },
{ name: 'Gargi Patel', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "Master of Design (M.Des) User Experience Design (UX), MIT Institute of Design (MIT ID)" },
{ name: 'Nilkanth Kadlag', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "Master’s of Science Computer Science (August 2023 - July 2025), University of Georgia, United States of America" },
{ name: 'Pradnya Rajendra Deore', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: "MBA General Management, Indian Institute of Management Visakhapatnam" },
{ name: 'Mohammad Bohra', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: "M.Tech Micro Electronics and VLSI Design, IIT Bombay" },
{ name: 'Soumitya Sanjay Patil', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: "MS Infotech (Embedded Systems), University of Stuttgart" },
{ name: 'Anuj Kiran Bhole', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: "MS Computer Science, University of Sydney" },
{ name: 'Rishabh Sharma', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: "ME Electrical Engineering and Embedded Systems, Ravensburg Weingarten University of Applied Sciences" },
{ name: 'Ruchita Pame', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: "Applied for MS Data Science, UC Boulder & Texas A&M" },
{ name: 'Yash Rajesh Meshram', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: "Higher Studies Information Not Available" },
{ name: 'Nandini Suresh Sharma', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: "MS Engineering Management, California State University East Bay" },
{ name: 'Aditi Yogesh Vaidya', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: "MS Engineering Management, California State University" },
{ name: 'Onkar Tukaram Bobade', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: "M.Tech Microelectronics and VLSI, IIT Hyderabad" },
{ name: 'Arin Ashish Jain', department: 'Electronics and Telecommunication Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: "M.Tech Micro Electronics and VLSI Design, National Institute of Technology Calicut" },
{ name: 'Shreya Desai', department: 'Electronics and Telecommunication Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: "MS Embedded Systems, Technische Universität Chemnitz, Germany" },
{ name: 'Vibhav Jagdish Dalvi', department: 'Electronics and Telecommunication Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: "MS Engineering Management, Northeastern University" },
{ name: 'Tushar Sadanand Alande', department: 'Electronics and Telecommunication Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: "M.Tech Automotive Electronics, Vellore Institute of Technology Vellore" },
{ name: 'Parth Jayant More', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "MS Internet of Things, Northeastern University" },
];
