const regularAlumni = [
{ name: 'Aarya Hire', department: 'Computer Science and Engineering (AI-ML)', year: '2025', photo: 'images/default-avatar.jpg', description: "Masters of Global Business (2025–2027), S P Jain School of Global Management" },
{ name: 'Dhanashree Suresh Yadav', department: 'Computer Science and Engineering (AI-ML)', year: '2025', photo: 'images/default-avatar.jpg', description: "M.Tech in Data Science (2025–2027), COEP Technological University, Pune" },

{ name: 'Gaurav Mahale', department: 'Computer Engineering REGIONAL', year: '2025', photo: 'images/default-avatar.jpg', description: 'MS in Data Science (2025–26, Pursuing), University of Glasgow, UK' },

{ name: 'Anandkumar Birajdar', department: 'Information Technology Engineering', year: '2006', photo: 'images/default-avatar.jpg', description: 'Assistant Professor, PCCOE' },
{ name: 'Ajinkya Waghulde', department: 'Information Technology Engineering', year: '2009', photo: 'images/default-avatar.jpg', description: 'MS CS - Game Development (2011-2013), University of Southern California' },
{ name: 'Ninad Oak', department: 'Information Technology Engineering', year: '2011', photo: 'images/default-avatar.jpg', description: 'University of Pennsylvania, US' },
{ name: 'Tejas Sanjay Desale', department: 'Information Technology Engineering', year: '2014', photo: 'images/default-avatar.jpg', description: 'Central Institute of Road Transport' },
{ name: 'Sagar Deshmukh', department: 'Information Technology Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'MBA, D Y Patil PGDM Institute, Assistant Professor, Pune Business School' },
{ name: 'Rhuta Joshi', department: 'Information Technology Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MSE in Computer Graphics and Gaming (2021-2023)' },
{ name: 'Shivani Birajdar', department: 'Information Technology Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MS Human Computer Interaction (2022-2023), University of California' },
{ name: 'Shambhavi Mokadam', department: 'Information Technology Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'MS Information System Management (2025), Carnegie Mellon University, US' },
{ name: 'Aditya Padgal', department: 'Information Technology Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'MS (2024-2025), Indiana University, US' },
{ name: 'Atharva Vijay Jadhav', department: 'Information Technology Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'MS (2023), RWTH Aachen University, Germany' },
{ name: 'Yash Joshi', department: 'Information Technology Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'MSc Media Informatics (2021-2024), RWTH Aachen, Germany' },
{ name: 'Amol Rajendra Angre', department: 'Information Technology Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'M.Tech' },
{ name: 'Bhushan Mohol', department: 'Information Technology Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS in AI, National University of Singapore' },
{ name: 'Nupoor Kulkarni', department: 'Information Technology Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS CS (Oct 2023 - Sept 2025), Saarland University, Germany' },
{ name: 'Abhishek Bharne', department: 'Information Technology Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MBA' },
{ name: 'Shaunak Tripathi', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS (2024), Illinois Institute of Technology, Chicago, US' },
{ name: 'Sakshi Pawar', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS (2024), Universities of Texas, US' },
{ name: 'Deep Ramdave', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MBA (2023-2025), IIT Delhi, India' },
{ name: 'Shivam Desale', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS (2024), San Diego State University, California, US' },
{ name: 'Mihir Amode', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MBA (2024-2025), SIES College of Management Studies, Mumbai, India' },
{ name: 'Ajinkya Dhainje', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS CS, University of Warwick, UK' },
{ name: 'Mandar Rao', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS Cyber Security (2024-2025), University of Washington Bothell, US' },
{ name: 'Jainam Jain', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS, University of Buffalo, US' },
{ name: 'Mohammad Abdul Mughni', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS AI (2024-2025), Anglia Ruskin University, UK' },
{ name: 'Darshan Phaldesai', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS Computer Software Engineering (2025-2026), Arizona State University, US' },
{ name: 'Karan Kavatage', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS CS (2025-2026), California State University, US' },
{ name: 'Shantanu Zadbuke', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS SE, San Jose State University, US' },
{ name: 'Divya Rajput', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS CS, University of Southern California, US' },
{ name: 'Shakyadeep Khobragade', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MBA (2023-2025)' },
{ name: 'Devika Nikam', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS (2023-2024), UK' },
{ name: 'Janhavi Dhajekar', department: 'Information Technology Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2024)' },
{ name: 'Shreyas Wetal', department: 'Information Technology Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2024), University of Sydney, Australia' },
{ name: 'Yash Tembhurnikar', department: 'Information Technology Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2025), Purdue University' },
{ name: 'Pratiksha Kashid', department: 'Information Technology Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2025), UNSW Sydney' },
{ name: 'Divyank Panwar', department: 'Information Technology Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (2025-26, Pursuing), IIT Kanpur' },
{ name: 'Pooja Nemade', department: 'Information Technology Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MS (2025-26, Pursuing), Buffalo University' },
{ name: 'Trisha Navani', department: 'Information Technology Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (2025-26, Pursuing), PCCOE' },

{ name: 'Prathamesh Bacchav', department: 'Computer Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MBA (2025)' },
{ name: 'Sarthak Phulari', department: 'Computer Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (2025)' },
{ name: 'Makardhwaj Kamble', department: 'Computer Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (2025)' },
{ name: 'Ankita Anarase', department: 'Computer Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MS (2025)' },
{ name: 'Pranav Patil', department: 'Computer Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (2025)' },
{ name: 'Hardik Jain', department: 'Computer Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech (2024)' },
{ name: 'Kuldeep Lakhe', department: 'Computer Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech (2024)' },
{ name: 'Saee Chormunge', department: 'Computer Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech (2024)' },
{ name: 'Sharvari Kale', department: 'Computer Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2024)' },
{ name: 'Apeksha Mulimani', department: 'Computer Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2024)' },
{ name: 'Bhagyesha Patil', department: 'Computer Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2024)' },
{ name: 'Pratik Patik', department: 'Computer Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2024)' },
{ name: 'Tanvi Mehta', department: 'Computer Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS' },
{ name: 'Chinmay Singhaniya', department: 'Computer Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS' },
{ name: 'Owais Mirza', department: 'Computer Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS' },
{ name: 'Amisha Sherekar', department: 'Computer Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS' },
{ name: 'Ovee Manolkar', department: 'Computer Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS' },
{ name: 'Aman Ramani', department: 'Computer Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS' },
{ name: 'Vedant Nerkar', department: 'Computer Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'M.Tech' },
{ name: 'Mohit Gandhi', department: 'Computer Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS' },
{ name: 'Ashish Kulkarni', department: 'Computer Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'M.Tech' },
{ name: 'Sakshi Kshirsagar', department: 'Computer Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS' },
{ name: 'Niraj Sawant', department: 'Computer Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS' },
{ name: 'Vishal Pange', department: 'Computer Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS' },
{ name: 'Sumedh Joshi', department: 'Computer Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS' },
{ name: 'Yash Vibhute', department: 'Computer Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS' },

{ name: 'Anil Katte', department: 'Mechanical Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (Computational Mechanics), PCCoE, India' },
{ name: 'Pradnya Bhapkar', department: 'Mechanical Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (Computational Mechanics), PCCoE, India' },
{ name: 'Chaitanya Kulkarni', department: 'Mechanical Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (Aerospace Engineering), DIAT-DRDO, India' },
{ name: 'Parth Deshmukh', department: 'Mechanical Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (Mechanical Engineering), DIAT-DRDO, India' },
{ name: 'Aditya Kotwal', department: 'Mechanical Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (Thermal Engineering), IIT Delhi, India' },
{ name: 'Ninad Acharya', department: 'Mechanical Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (Manufacturing Engineering), NIT Warangal, India' },
{ name: 'Mihir Amit Bhansali', department: 'Mechanical Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS Applied Data Science, University of Florida, USA' },
{ name: 'Avanti Sadashiv Ingale', department: 'Mechanical Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MBA, DY Patil University Pune, India' },
{ name: 'Siddharth Dnyaneshwar Bandawane', department: 'Mechanical Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'UG Researcher, University of Wisconsin-Madison, USA' },
{ name: 'Daivik Chandrabhan Baviskar', department: 'Mechanical Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'Indian Maritime University Mumbai, India' },
{ name: 'Kaustubh Devidas Damdhar', department: 'Mechanical Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'University of Mumbai, India' },
{ name: 'Govind Manojkumar Bagdiya', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'PGD-ERP, COEP, India' },
{ name: 'Nishigandha Ganesh Darekar', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS, Technische Universität Berlin, Germany' },
{ name: 'Varun Shriram Gawade', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MIM, ESSEC Business School, France' },
{ name: 'Vaishnav Ravindra Kaldate', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MEng, University of Massachusetts Amherst, USA' },
{ name: 'Akash Rajesh More', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'PGDM, ISBS Pune, India' },
{ name: 'Sanket Rajesh Nampurkar', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MSc, University of Manchester, UK' },
{ name: 'Tanishq Vijaykumar Patil', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'Masters Degree' },
{ name: 'Aditya Sunil Wake', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'Masters Degree' },
{ name: 'Rohan Ravindra Kharat', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'M.Tech, COEP Pune, India' },
{ name: 'Adwait Deepak Kulkarni', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS Robotics, Boston University, USA' },
{ name: 'Anuja Sunil Rupnar', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS Mechanical Engineering, Worcester Polytechnic Institute, USA' },
{ name: 'Om Vitthalrao Sangle', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS Mechanical & Process Engineering, TU Bergakademie Freiberg, Germany' },
{ name: 'Soniya Ramesh Shah', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS Engineering Management, Texas A&M University, USA' },
{ name: 'Rohit Rajesh Pawar', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'Masters, Aston University, UK' },
{ name: 'Aniket Waman Didare', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS Science, IIT Madras, India' },
{ name: 'Shreedhar Vijay Lohar', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'M.Tech Mechatronics, COEP Technological University, India' },
{ name: 'Nimish Nitin Mahadar', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS, Arizona State University, USA' },
{ name: 'Jeswin Gigi Mathew', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'Masters Mechanical Engineering, Technological University Dublin, Ireland' },
{ name: 'Saurabh Deepak Ramayane', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MBA, DY Patil Institute of Distance Learning, India' },
{ name: 'Aamod Vinayak Pande', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'ME Robotics, Mechatronics and Automation, RMIT University, Australia' },
{ name: 'Amey Ravindra Thonge', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'ME Automotive Engineering, Technische Hochschule Ingolstadt, Germany' },
{ name: 'Chaitanya Digambar Kshirsagar', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Big Data Analytics, SunBeam Institute of Information Technology, India' },
{ name: 'Tejas Gulabrao Chavan', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MBA HR & Services, Savitribai Phule Pune University, India' },
{ name: 'Nachiket Sagar Deshpande', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'ME Industrial Management, University of Southern California, USA' },
{ name: 'Prajwal Tryambakrao Dhote', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MBA, K J Somaiya Institute, India' },
{ name: 'Piyush Jitesh Gonal', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Masters Forecast & Technology Management, Technische Hochschule Ingolstadt, Germany' },
{ name: 'Saurabh Mahesh Jadhav', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Masters Automotive Engineering, Technische Hochschule Ingolstadt, Germany' },
{ name: 'Malhar Rahul Khole', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MTech Material Science & Technology, IIT Varanasi, India' },
{ name: 'Mehul Vinayak Mane', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MTech Designing, MIT-WPU, India' },
{ name: 'Akash Girish Guggari', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'ME Logistics, Materials & Supply Chain, Berlin School of Business & Innovation, Germany' },
{ name: 'Harshal Harischandra Meher', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MBA, IIM Lucknow, India' },
{ name: 'Umesh Rajshekhar Nandargi', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'ME Automotive Systems, Hochschule Esslingen University, Germany' },
{ name: 'Atharv Rajesh Nirhali', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'ME Industrial Engineering, Northeastern University, USA' },
{ name: 'Ojas Jaiprakash Vishwakarma', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS Renewable Energy Systems, Hamburg University of Applied Sciences, Germany' },
{ name: 'Pranita Umesh Pachkawade', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS Sustainable Energy Systems, University of Freiburg, Germany' },
{ name: 'Akanksha Prakash Pawar', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS Engineering & Management, Technische Hochschule Ingolstadt, Germany' },
{ name: 'Tushar Badrinath Rane', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MBA Operations Management, NMIMS CDOE, India' },
{ name: 'Ruturaj Prashant Yawale', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'ME International Automotive Engineering, Technische Hochschule Ingolstadt, Germany' },
{ name: 'Sakshi Ganesh Shende', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS Mechanical Engineering, New York University, USA' },
{ name: 'Saurabh Suryakant Nagendra', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MTech Computer Integrated Manufacturing, NIT Warangal, India' },
{ name: 'Hrishikesh Suhas Shintre', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Business Administration, Sydenham Institute of Management Studies, India' },
{ name: 'Shreyash Shrikant Kulkarni', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Masters Logistics & Supply Chain Management, University of Warwick, UK' },
{ name: 'Pranav Tukaram Tathe', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MBA, IIM Calcutta, India' },
{ name: 'Digvijay Chandrasen Thakare', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Machine Design, IIT Guwahati, India' },
{ name: 'Prajwal Vijay Thorat', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Electric Vehicles, MIT ADT University, India' },
{ name: 'Urvesh Vikhiat Berry', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Business Management, London Business School, UK' },
{ name: 'Tanmay Rajesh Vinchavekar', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Management Studies, Jamnalal Institute of Management Studies, India' },
{ name: 'Rugved Sharadrao Wankhade', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Marketing Management, Indira School of Business Studies PGDM, India' },
{ name: 'Prathamesh Pralhad Pawar', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Management, IIT Kanpur, India' },
{ name: 'Nikhil Chhotu Somwanshi', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Management & Business Analytics, IISc Bangalore, India' },
{ name: 'Ranbirsingh Manmitsingh Saini', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Engineering Management, University of Leicester, UK' },
{ name: 'Aditya Pramod Palande', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Industrial Engineering, Penn State University, USA' },
{ name: 'Aditya Ravi Jadhav', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Management, ESCP Business School, Germany/Spain' },
{ name: 'Atharva Ajay Deshpande', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Mechanical Engineering, New York University, USA' },
{ name: 'Pratik Janardan Avhad', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Mechanical Engineering, PCCoE, India' },
{ name: 'Atharva Ravindra Bhorpe', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Mechatronics Robotics & Automation, RWTH Aachen University, Germany' },
{ name: 'Pranav Pradip Chandugade', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Supply Chain Management, SRH University, Germany' },
{ name: 'Soham Shrish Kharkar', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Computer Aided Mechanical Engineering, RWTH Aachen University, Germany' },
{ name: 'Pranav Prashant Dahiwade', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Management, Frankfurt School of Finance & Management, Germany' },
{ name: 'Anjali Sanjay Raut', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Supply Chain & Logistics Management, University of Warwick, UK' },
{ name: 'Siddharth Vinayak Shrotri', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Mechatronics Automation & Robotics, Worcester Polytechnic Institute, USA' },
{ name: 'Suvid Sanjay Shinde', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Robotic Systems Engineering, RWTH Aachen University, Germany' },
{ name: 'Amey Pravin Talegaonkar', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Management, Imperial College Business School, UK' },
{ name: 'Vaishnavi Bhalchandra Kasar', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Industrial Engineering, North Carolina State University, USA' },
{ name: 'Hritika Sanjay Waghjale', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Industrial Engineering, Penn State University, USA' },
{ name: 'Ganesh Abhay Bharambe', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Business Administration, PUMBA (Department of Management Science), India' },
{ name: 'Ritesh Lalu Patil', department: 'Mechanical Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech Nuclear Science & Engineering, Homi Bhabha National Institute, India' },
{ name: 'Shubhada Santosh Padwal', department: 'Mechanical Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MS Management, Technical University of Munich, Germany' },
{ name: 'Yash Naseri', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MBA International Business, MDI Gurgaon, India' },
{ name: 'Mridhul Iyer', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS Quantitative Economics, Indian Statistical Institute Kolkata, India' },
{ name: 'Om Anant Kulkarni', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS Aerospace Engineering, Technical University of Munich, Germany' },
{ name: 'Yash Nitin Patil', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Masters Engineering Management, Duke University, USA' },
{ name: 'Shivam Panjab Hake', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'M.Tech Mobility Engineering, IISc Bangalore, India' },
{ name: 'Lakhan Ashok Patil', department: 'Mechanical Engineering', year: '2012', photo: 'images/default-avatar.jpg', description: 'State Tax Inspector (STI), Maharashtra State GST Department' },
{ name: 'Ajay Bhujbal', department: 'Mechanical Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'Scientist SC (Group A Gazetted Post), ISRO' },


{ name: 'Miss. Vijaya Ghatol', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MBA in Sustainable Energy Management (2025–26), NICMAR, Pune, India' },
{ name: 'Ganesh Kodnani', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MBA in Advanced Construction Management (2025–26), NICMAR, Pune, India' },
{ name: 'Manas Tendulkar', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MBA in Advanced Construction Management (2025–26), NICMAR, Pune, India' },
{ name: 'Tejas Solunke', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MBA in Advanced Construction Management (2025–26), NICMAR, Pune, India' },
{ name: 'Gurkiratsingh Arora', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MTech in Computer Aided Structural Engineering (2025–26), IIIT Hyderabad, India' },
{ name: 'Devesh Patil', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MSc in Construction Management (2025–26), University of Birmingham, Dubai' },
{ name: 'Vaishnavi Patil', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MTech in Town Planning (2025–26), COEP Technical University, Pune, India' },
{ name: 'Onkar Kusmade', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MTech in Structures (2025–26), IIT Madras, India' },
{ name: 'Varun Desai', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MS in Building Construction and Facilities Management (2025–26), Georgia Tech, Atlanta' },
{ name: 'Aditya Tatiya', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MS in Master of Business Analytics (2025–26), University of Technology Sydney' },
{ name: 'Harsh Gangwal', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS in Construction Management (2024–25), Texas A&M University, USA' },
{ name: 'Milind Patil', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MTech in Transportation Engineering (2024–25), COEP Technical University, Pune, India' },
{ name: 'Dhwani Ramawat', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MTech in Professional Project Management (2024–25), IIT Delhi, India' },
{ name: 'Shraddhesh Shirode', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MTech in Structural Engineering (2024–25), K. K. Wagh, Nashik, India' },
{ name: 'Apurva Suryawanshi', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management (2024–25), NICMAR, Pune, India' },
{ name: 'Ishika Suryawanshi', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management (2024–25), NICMAR, Pune, India' },
{ name: 'Raj Peswani', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS in Analytics (2024–25), UC Berkeley, USA' },
{ name: 'Bhavesh Mahajan', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management (2024–25), VJTI Mumbai, India' },
{ name: 'Nishant Kad', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management (2024–25), COEP Technical University, Pune, India' },
{ name: 'Vishal Lad', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management (2024–25), COEP Technical University, Pune, India' },
{ name: 'Pratham Agarwal', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MBA in Advanced Construction Management (2023–24), NICMAR, Pune, India' },
{ name: 'Purvesh Bhole', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'ME in Structural Engineering (2023–24), Pravara Rural College of Engineering, Loni, India' },
{ name: 'Prathamesh Gurav', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS in Structural Engineering (2023–24), Texas A&M University, USA' },
{ name: 'Pushpak Joshi', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech in Structural Engineering (2023–24), Sardar Patel College of Engineering, Mumbai, India' },
{ name: 'Mansi Lonkar', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MBA in General Management (2023–24), IIT Kanpur, India' },
{ name: 'Kartik Waghere', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS in Construction Management (2023–24), University of Illinois, USA' },
{ name: 'Isha Mali', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech in Structural Engineering (2023–24), COEP Technical University, Pune, India' },
{ name: 'Kartik Patil', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS in Construction Management (2023–24), Texas A&M University, USA' },
{ name: 'Akshada Reur', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech in Environment and Water Resources Engineering (2023–24), COEP Technical University, Pune, India' },
{ name: 'Rutuja Patil', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech in Transportation Engineering (2023–24), COEP Technical University, Pune, India' },
{ name: 'Prachi Pawar', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Engineering and Management (2023–24), MIT WPU, Pune, India' },
{ name: 'Himanshu Thakur', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech in Structural Engineering (2023–24), MIT WPU, Pune, India' },
{ name: 'Harshavardhan Rathod', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech in Environmental Engineering (2023–24), Pune, India' },
{ name: 'Lalit Pandit', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech in Environmental Engineering (2023–24), Pune, India' },
{ name: 'Harshal Mali', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management (2023–24), Sandeep University, Nashik, India' },
{ name: 'Kaustubh Anchawale', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management (2023–24), Government College of Engineering, Karad, India' },
{ name: 'Sumedh Aher', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MTech in Structures (2022–23), BITS Hyderabad, India' },
{ name: 'Sawani Anwale', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MBA in HR Analytics (2022–23), XIME, India' },
{ name: 'Manjitsingh Girase', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MTech in Transportation Engineering (2022–23), IIT Powai Mumbai, India' },
{ name: 'Suyash Khemnar', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS in Construction Management (2022–23), Duke University, USA' },
{ name: 'Saurabh Patil', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS in Environmental Engineering & Pollution Control (2022–23), Griffith University, Australia' },
{ name: 'Aditya Sali', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MBA in Marketing (2022–23), SIBM Pune, India' },
{ name: 'Bhakti Kapse', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS (2022–23), University of California, Berkeley, USA' },
{ name: 'Raj Kene', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS (2022–23), University of California Riverside, USA' },
{ name: 'Tanmay Kadu', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS (2022–23), New York University, USA' },
{ name: 'Sayali Pawar', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS (2022–23), Purdue University, USA' },
{ name: 'Vedangi Patil', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS in Structural Engineering (2022–23), Texas A&M University, USA' },
{ name: 'Pooja Jat', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MTech in Structural Engineering (2022–23), MIT WPU, Pune, India' },
{ name: 'Swaraj Hanmante', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MSc in International Business and Strategy (2022–23), Lancaster University, UK' },
{ name: 'Gavhane Tushar Haribhau', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'ME (2021–22), AISSMS, Pune, India' },
{ name: 'Jagdhane Suraj Dhananjay', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'MS (2021–22), University of Texas at Arlington, USA' },
{ name: 'Karle Aishwarya Ramesh', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'ME in Structures (2021–22), JSPM, Pune, India' },
{ name: 'Poossery Pooja', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'ACM (2021–22), NICMAR, Pune, India' },
{ name: 'Shende Asha', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'MTech (2021–22), NIT Durgapur, India' },
{ name: 'Gaikwad Renuka', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'MTech (2021–22), COEP, Pune, India' },
{ name: 'Pophale Mrunal', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'MTech (2021–22), COEP, Pune, India' },
{ name: 'Hrutuja Chaudhari', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'MS in Energy Water Sustainable Technology (2021–22), Illinois University, USA' },
{ name: 'Sumedh Kharat', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'MS in Construction Management (2021–22), Purdue University, USA' },
{ name: 'Shinde Vaishnavi', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'MBA in Advanced Construction Management (2020–21), NICMAR, Pune, India' },
{ name: 'Viraj Bhandari', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'MS in Construction Management and Technology (2020–21), Arizona State University, USA' },
{ name: 'Shelke Ashwinkumar', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'ME in Structural Engineering (2020–21), PDVVP College of Engineering, Ahmednagar, India' },
{ name: 'Bajbalkar Mayuresh', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'MTech (2020–21), MIT-ADT University, Pune, India' },
{ name: 'Sonawane Hrushikesh', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'Higher Studies (2020–21), International Institute of Management and Science' },
{ name: 'Kalhapure Amruta', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'Post Graduation Program in Advanced Construction Management (2020–21), NICMAR, Pune, India' },
{ name: 'Sathone Manthan', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'Post Graduation Program in Advanced Construction Management (2020–21), NICMAR, Pune, India' },
{ name: 'More Ashwini', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'ME in Construction Technology and Management (2020–21), SGCOE&T Bhusawal, India' },
{ name: 'Chaitanya Chudiwal', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'MS (2020–21), University of Texas at Arlington, USA' },
{ name: 'Bhushan Bhavsar', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'Post Graduation Program in Advanced Construction Management (2020–21), NICMAR, Pune, India' },
{ name: 'Rohan Patil', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'Post Graduation Program in Advanced Construction Management (2020–21), NICMAR, Pune, India' },
{ name: 'Shubham Paymal', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'MTech in Structures (2020–21), MIT-WPU, Pune, India' },
{ name: 'Hitesh Patil', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'MS in Construction Management and Technology (2020–21), Arizona State University, USA' },
{ name: 'Rohit Datir', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'MS in Project Management (2020–21), Northeastern University, Boston, USA' },
{ name: 'Prajwal Nale', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'Post Graduation Program in Advanced Construction Management, NICMAR, Pune, India' },
{ name: 'Rohit Deokar', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'MTech in Construction and Management, MIT-WPU, Pune, India' },
{ name: 'Omkar Patil', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management, Sardar Patel College of Engineering, Mumbai, India' },
{ name: 'Kolge Ankit', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'Post Graduation Program in Advanced Construction Management, NICMAR, Pune, India' },
{ name: 'Yogita Patel', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MS in Water Science and Engineering, Karlsruhe Institute of Technology, Germany' },
{ name: 'Suraj Dabhade', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'Post Graduation Program in Quantity Survey and Contract Management, NICMAR, Pune, India' },
{ name: 'Gaikwad Manasi', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MS in Project Management, Northeastern University, Boston, USA' },
{ name: 'Sushant More', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MS in Transportation Engineering, Northeastern University, Boston, USA' },
{ name: 'Dipti More', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MS in Project Management, Northeastern University, Boston, USA' },
{ name: 'Deepali Tondare', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MS in Construction Management, Texas A&M University, USA' },
{ name: 'Shubham Bhadhane', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MS in Construction Management and Technology, Arizona State University, USA' },
{ name: 'Shubham Katore', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MS in Project Engineering and Management, NICMAR, Pune, India' },
{ name: 'Kunal Patil', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MS in Project Engineering and Management, NICMAR, Pune, India' },
{ name: 'Mayur Salunke', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MS in Information Studies, Texas A&M University, USA' },
{ name: 'Shriya Jadhav', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management, Sardar Patel College of Engineering, Mumbai, India' },
{ name: 'Aditya Sangle', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'PGDM, JAGSOM, Bangalore, India' },
{ name: 'Akshaykumar Shinde', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management, Government College of Engineering, Karad, India' },
{ name: 'Adhav Ankit', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MTech in Structural Engineering, College of Engineering, Pune, India' },
{ name: 'Bansode Pradnya', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management, Government College of Engineering, Karad, India' },
{ name: 'Basarkar Shubham', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MTech in Structural Engineering, VNIT Nagpur, India' },
{ name: 'Pore Tanvi Satish', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'MTech, VJTI Mumbai, India' },
{ name: 'Udhane Darshana Hemant', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'MS, Deakin University, Australia' },
{ name: 'Bedmutha Saurabh Nitin', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'MS, University of New South Wales, Australia' },
{ name: 'Mankhair Roshan Vilasrao', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'Higher Studies, IIT Powai Mumbai, India' },
{ name: 'Tapas Mahesh Ramesh', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'MS, East Carolina University, Greenville, USA' },
{ name: 'Roge Kartik Shantaram', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'MS, Deakin University, Australia' },
{ name: 'Malwade Aniket Prashant', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'MS, Deakin University, Australia' },
{ name: 'Kolte Rushikesh Rajesh', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'MS, MNIT Jaipur, India' },
{ name: 'Kadam Abhishek Dilip', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'Higher Studies, D Y Patil COE Akurdi, Pune, India' },
{ name: 'Karhadkar Shantanu C.', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'Higher Studies, RWTH Aachen University, Germany' },
{ name: 'Nerkar Monali Jyotiram', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'MTech, Government College of Engineering, Karad, India' },
{ name: 'Vinay Agarwal', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'MTech, NIT Warangal, India' },
{ name: 'Shubham Pawar', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'Higher Studies, Imperial College of Engineering and Research, India' },
{ name: 'Dhanbar Aditya', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'Higher Studies, Imperial College of Engineering and Research, India' },
{ name: 'Kunal Badhane', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'MS, Sandip University, India' },
{ name: 'Sachin Bhure', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'MTech, Imperial College of Engineering and Research, India' },
{ name: 'Harshal Rasal', department: 'Civil Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'MTech in Hydraulics and Water Resources Engineering, IIT Kharagpur, India' },
{ name: 'Ganesh Petkar', department: 'Civil Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'MTech in Transportation Engineering, VNIT Nagpur, India' },
{ name: 'Nilay Warkhedkar', department: 'Civil Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'MS in Environmental Engineering' },
{ name: 'Tejaswini Mankar', department: 'Civil Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'MTech in Environmental Engineering, D Y Patil College of Engineering, Akurdi, India' },
{ name: 'Pawan Chagedia', department: 'Civil Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'MTech in Structural Engineering, NIT Hamirpur, India' },
{ name: 'Mahesh Jamdade', department: 'Civil Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'Higher Studies, NICMAR, Pune, India' },
{ name: 'Allen Gilbert', department: 'Civil Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'MS in Project Management, De Montfort University, Leicester, UK' },
{ name: 'Ambaresh Tejari', department: 'Civil Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'MS' },
{ name: 'Shashank Kadu', department: 'Civil Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'Post Graduation Program in Project Engineering Management, NICMAR, Pune, India' },
{ name: 'Parag Mahajan', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'MTech in Water Resources Engineering, Government College of Engineering, Aurangabad, India' },
{ name: 'Juzer Shaikh', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'Post Doc / PhD / MTech in Earth Sciences, Indian Institute of Science, Bangalore, India' },
{ name: 'Rushikesh Kasar', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management' },
{ name: 'Bhagyarekha Jadhav', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'MTech in Water Resources Engineering, Government College of Engineering, Aurangabad, India' },
{ name: 'Abhishek Mahajan', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management, VJTI Mumbai, India' },
{ name: 'Akshay Bagal', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management, D Y Patil Ambi, Talegaon, India' },
{ name: 'Bhushan Malusare', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management, D Y Patil Ambi, Talegaon, India' },
{ name: 'Samruddhi Patil', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'Junior Engineer' },
{ name: 'Nikhil Bhagwanrao Patil', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'Water Conservation Officer (Grade B)' },
{ name: 'Lt. Shivam Subhash Bondre', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Indian Army Officer' },
{ name: 'Shubham Kadam', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'Junior Engineer' },
{ name: 'Vitthal Shelke', department: 'Civil Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'Assistant Engineer GR-II' },
{ name: 'Siddhi Kadam', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'Civil Engineering Assistant' },
{ name: 'Kunal Bhadane', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'Civil Engineering Assistant' },
{ name: 'Lovkesh Bhosale', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'Junior Engineer' },
{ name: 'Shital Dake', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'Assistant Engineer Grade-II' },
{ name: 'Sushil Biradar', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'Water Conservation Officer' },
{ name: 'Pramila Pardhi', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'Civil Engineering Assistant' },
{ name: 'Anuja Vijay Sawardekar', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Water Conservation Officer' },
{ name: 'Girish Patil', department: 'Civil Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'Assistant Engineer (Gr II)' },
{ name: 'Dhananjay Gaonkar', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'Assistant Executive Engineer' },
{ name: 'Vanshaj Wadhwa', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'Major, Indian Army' },
{ name: 'Aniket Patil', department: 'Civil Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'Assistant Engineer Gr-2 (Gazetted)' },
{ name: 'Akash Nagane', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'Assistant Engineer' },
{ name: 'Ashish Methekar', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'Assistant Engineer (Civil)' },
{ name: 'Pushkaraj Mane', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'Civil Engineering Assistant' },
{ name: 'Vishwajit Sarwale', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'Civil Engineering Assistant' },
{ name: 'Kunal Rajendra Sonawane', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'Civil Engineering Assistant' },
{ name: 'Parimal Sinalkar', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'Civil Engineering Assistant' },
{ name: 'Aparna Suresh Gaikwad', department: 'Civil Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'Civil Engineering Assistant' },
{ name: 'Bhagyarekha Jadhav', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'Assistant Engineer Class-II' },
{ name: 'Aditya Katkade', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'Junior Engineer' },
{ name: 'Tejaswini Bagul', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'Junior Engineer' },
{ name: 'Rahul Randive', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'Municipal Engineer' },
{ name: 'Kamlesh Zinjurke', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'Assistant Engineer Grade-II' },
{ name: 'Prathmesh Solapure', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'Senior Operations Officer' },
{ name: 'Tejas Borse', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'Assistant Engineer Grade-II' },
{ name: 'Apurva Shinde', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'Civil Engineering Assistant' },
{ name: 'Avishkar Doke', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'Junior Engineer' },
{ name: 'Rahul Sanap', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'Planning Engineer' },
{ name: 'Rahul Latpate', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'Junior Engineer' },
{ name: 'Rushikesh Ravindra Kasar', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'Sectional Engineer' },
{ name: 'Sunanda Dhindale', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'Junior Engineer' },
{ name: 'Er. Rohit Bhat', department: 'Civil Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'Assistant Engineer Grade-II' },
{ name: 'Sudarshan Yadav', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Sub Divisional Officer' },
{ name: 'Kaldate Nishant', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'Sub Divisional Officer' },
{ name: 'Madhav Kamble', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'Junior Engineer' },
{ name: 'Swapnil Valekar', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'Water Conservation Officer' },
{ name: 'Avinash Bogulwar', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'Water Conservation Officer' },
{ name: 'Dnyaneshwar Tandale', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'Junior Engineer' },
{ name: 'Yogesh Shivlal Sharma', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'Sub Divisional Officer (WRD)' },
{ name: 'Vikash Kumar Sharma', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'Major, Indian Army' },
{ name: 'Rajnish Jayashree Bariya', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'Sectional Engineer' },
{ name: 'Aishwarya Karle', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'Assistant Junior Engineer' },
{ name: 'Prithviraj Sanjeev Sawant', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'Sectional Engineer' },
{ name: 'Aditya Karad', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'Senior Operations Officer' },
{ name: 'Omkar Patil', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'M.Tech Construction Management, Sardar Patel College of Engineering Mumbai' },

{ name: 'Arin Ashish Jain', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech Micro Electronics and VLSI Design (2025-2027), National Institute of Technology Calicut, India' },
{ name: 'Shreya Rajendra Desai', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.S. in Embedded System, Chemnitz Technical University, Germany' },
{ name: 'Janhavi Chati', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MSc Electronics Engineering, University of Southampton, England' },
{ name: 'Pradnya Rajendra Deore', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MBA General Management (2025-2027), Indian Institute of Management Visakhapatnam, India' },
{ name: 'Mohammad Bohra', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech Micro Electronics and VLSI Design (Solid State Devices) (2025-2027), IIT Bombay, India' },
{ name: 'Onkar Tukaram Bobade', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech Microelectronics and VLSI (2026-2028), IIT Hyderabad, India' },
{ name: 'Soumitya Sanjay Patil', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS Infotech (Embedded Systems) (2026-2028), University of Stuttgart, Germany' },
{ name: 'Nilkanth Kadlag', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "Master’s of Science Computer Science (August 2023 - July 2025), University of Georgia, United States of America" },
{ name: 'Sandeep Sharma', department: 'Electronics and Telecommunication Engineering', year: '2008', photo: 'images/default-avatar.jpg', description: "MS ECE (Electrical and Computer Engineering), Missouri University of Science and Technology" },
{ name: 'Jaydeep Ananda Mohite', department: 'Electronics and Telecommunication Engineering', year: '2010', photo: 'images/default-avatar.jpg', description: "M.Tech Electronics Engineering, Walchand College of Engineering Sangli" },
{ name: 'Dr. Mane Harshali Dnyaneshwar', department: 'Electronics and Telecommunication Engineering', year: '2011', photo: 'images/default-avatar.jpg', description: "PhD Signal Processing, K L University" },
{ name: 'Jaywant Kamble', department: 'Electronics and Telecommunication Engineering', year: '2013', photo: 'images/default-avatar.jpg', description: "ME VLSI and Embedded Systems, Pune University" },
{ name: 'Sailee Borse', department: 'Electronics and Telecommunication Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: "MBA General, Indian Institute of Management Kozhikode" },
{ name: 'Shreekanya Kodate', department: 'Electronics and Telecommunication Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: "M.Tech Communication Engineering, Indian Institute of Technology Bombay" },
{ name: 'Shalvraj Dhananjay Kulkarni', department: 'Electronics and Telecommunication Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: "M.Tech Automotive Electronics, VIT Vellore (University Gold Medalist)" },
{ name: 'Siddhi Gaikwad', department: 'Electronics and Telecommunication Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: "M.Sc. Electronic Information Engineering, Trinity College Dublin" },
{ name: 'Mahesh Balasaheb Raut', department: 'Electronics and Telecommunication Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: "Masters Data Science, University of Guelph" },
{ name: 'Antara Deepak Muley', department: 'Electronics and Telecommunication Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: "MS Electrical and Computer Engineering, Michigan Technological University" },
{ name: 'Harshit Sampgaon', department: 'Electronics and Telecommunication Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: "MS Electrical and Computer Engineering - Machine Learning, Northeastern University" },
{ name: 'Snehal Patil', department: 'Electronics and Telecommunication Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: "MS Electrical Engineering, California State University Fullerton" },
{ name: 'Gaurree Lohiya', department: 'Electronics and Telecommunication Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: "MS Engineering Management, University of Illinois at Urbana Champaign" },
{ name: 'Nikhil Samir Bhosale', department: 'Electronics and Telecommunication Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: "MS Data Science and Analytics, Illinois Institute of Technology" },
{ name: 'Raviraj Mahadeo Khopade', department: 'Electronics and Telecommunication Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: "MS Computer Science, Illinois Institute of Technology" },
{ name: 'Aniket Chopade', department: 'Electronics and Telecommunication Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: "MS Computer Engineering, San Jose State University" },
{ name: 'Akash Rajesh Biyani', department: 'Electronics and Telecommunication Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: "MSc Embedded Computing System, University of Southampton & RPTU Kaiserslautern" },
{ name: 'Shounak Rajendra Powar', department: 'Electronics and Telecommunication Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: "MS Computer Science, Iowa State University" },
{ name: 'Shashank Tiwari', department: 'Electronics and Telecommunication Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: "MBA Human Resource Management, XLRI Jamshedpur" },
{ name: 'Utkarsha Vikas Chinchore', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "MS Mechatronics, KTH Royal Institute of Technology Sweden" },
{ name: 'Jaiee Anand Bhange', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "Master of Information Technology - Artificial Intelligence, University of New South Wales Sydney" },
{ name: 'Chirag Ramesh Kharche', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "MS Electrical Engineering - Power Electronics, Virginia Tech" },
{ name: 'Tushar Subhash Alase', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "MS Electrical & Computer Engineering, Purdue University" },
{ name: 'Shubham Rajesh Kumar Das', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "Ph.D. Theoretical Physics, The Institute of Mathematical Sciences (IMSc)" },
{ name: 'Gargi Patel', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "Master of Design (M.Des) User Experience Design (UX), MIT Institute of Design (MIT ID)" },
{ name: 'Anuj Kiran Bhole', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: "MS Computer Science, University of Sydney" },
{ name: 'Rishabh Sharma', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: "ME Electrical Engineering and Embedded Systems, Ravensburg Weingarten University of Applied Sciences" },
{ name: 'Ruchita Pame', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: "Applied for MS Data Science, UC Boulder & Texas A&M" },
{ name: 'Yash Rajesh Meshram', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: "Higher Studies Information Not Available" },
{ name: 'Nandini Suresh Sharma', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: "MS Engineering Management, California State University East Bay" },
{ name: 'Aditi Yogesh Vaidya', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: "MS Engineering Management, California State University" },
{ name: 'Arin Ashish Jain', department: 'Electronics and Telecommunication Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech Micro Electronics and VLSI Design, National Institute of Technology Calicut (NIRF Rank 21)' },
{ name: 'Shreya Desai', department: 'Electronics and Telecommunication Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MS Embedded Systems, Technische Universität Chemnitz, Germany (Top universities for employability)' },
{ name: 'Vibhav Jagdish Dalvi', department: 'Electronics and Telecommunication Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MS Engineering Management, Northeastern University, USA (Rank 384)' },
{ name: 'Tushar Sadanand Alande', department: 'Electronics and Telecommunication Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech Automotive Electronics, Vellore Institute of Technology Vellore (NIRF 2025 Rank 16)' },
{ name: 'Janhavi Chati', department: 'Electronics and Telecommunication Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MSc Electronics Engineering, University of Southampton, England' },
{ name: 'Parth Jayant More', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "MS Internet of Things, Northeastern University" },
];





