const regularAlumni = [
{ name: 'Aarya Hire', department: 'Computer Science and Engineering (AI-ML)', year: '2025', photo: 'images/default-avatar.jpg', description: "Masters of Global Business (2025–2027), S P Jain School of Global Management" },
{ name: 'Dhanashree Suresh Yadav', department: 'Computer Science and Engineering (AI-ML)', year: '2025', photo: 'images/default-avatar.jpg', description: "M.Tech in Data Science (2025–2027), COEP Technological University, Pune" },

{ name: 'Gaurav Mahale', department: 'Computer Engineering REGIONAL', year: '2025', photo: 'images/default-avatar.jpg', description: 'MS in Data Science (2025–26, Pursuing), University of Glasgow, UK' },

{ name: 'Anandkumar Birajdar', department: 'Information Technology Engineering', year: '2006', photo: 'images/default-avatar.jpg', description: 'Assistant Professor, PCCOE' },
{ name: 'Ajinkya Waghulde', department: 'Information Technology Engineering', year: '2009', photo: 'images/default-avatar.jpg', description: 'MS CS - Game Development (2011-2013), University of Southern California' },
{ name: 'Ninad Oak', department: 'Information Technology Engineering', year: '2011', photo: 'images/default-avatar.jpg', description: 'University of Pennsylvania, US' },
{ name: 'Tejas Sanjay Desale', department: 'Information Technology Engineering', year: '2014', photo: 'images/default-avatar.jpg', description: 'Central Institute of Road Transport' },
{ name: 'Sagar Deshmukh', department: 'Information Technology Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'MBA, D Y Patil PGDM Institute, Assistant Professor, Pune Business School' },
{ name: 'Rhuta Joshi', department: 'Information Technology Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MSE in Computer Graphics and Gaming (2021-2023)' },
{ name: 'Shivani Birajdar', department: 'Information Technology Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MS Human Computer Interaction (2022-2023), University of California' },
{ name: 'Shambhavi Mokadam', department: 'Information Technology Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'MS Information System Management (2025), Carnegie Mellon University, US' },
{ name: 'Aditya Padgal', department: 'Information Technology Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'MS (2024-2025), Indiana University, US' },
{ name: 'Atharva Vijay Jadhav', department: 'Information Technology Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'MS (2023), RWTH Aachen University, Germany' },
{ name: 'Yash Joshi', department: 'Information Technology Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'MSc Media Informatics (2021-2024), RWTH Aachen, Germany' },
{ name: 'Bhushan Mohol', department: 'Information Technology Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS in AI, National University of Singapore' },
{ name: 'Nupoor Kulkarni', department: 'Information Technology Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS CS (Oct 2023 - Sept 2025), Saarland University, Germany' },
{ name: 'Abhishek Bharne', department: 'Information Technology Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MBA' },
{ name: 'Shaunak Tripathi', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS (2024), Illinois Institute of Technology, Chicago, US' },
{ name: 'Sakshi Pawar', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS (2024), Universities of Texas, US' },
{ name: 'Deep Ramdave', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MBA (2023-2025), IIT Delhi, India' },
{ name: 'Shivam Desale', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS (2024), San Diego State University, California, US' },
{ name: 'Mihir Amode', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MBA (2024-2025), SIES College of Management Studies, Mumbai, India' },
{ name: 'Ajinkya Dhainje', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS CS, University of Warwick, UK' },
{ name: 'Mandar Rao', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS Cyber Security (2024-2025), University of Washington Bothell, US' },
{ name: 'Jainam Jain', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS, University of Buffalo, US' },
{ name: 'Mohammad Abdul Mughni', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS AI (2024-2025), Anglia Ruskin University, UK' },
{ name: 'Darshan Phaldesai', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS Computer Software Engineering (2025-2026), Arizona State University, US' },
{ name: 'Karan Kavatage', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS CS (2025-2026), California State University, US' },
{ name: 'Shantanu Zadbuke', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS SE, San Jose State University, US' },
{ name: 'Divya Rajput', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS CS, University of Southern California, US' },
{ name: 'Shakyadeep Khobragade', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MBA (2023-2025)' },
{ name: 'Devika Nikam', department: 'Information Technology Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS (2023-2024), UK' },
{ name: 'Janhavi Dhajekar', department: 'Information Technology Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2024)' },
{ name: 'Shreyas Wetal', department: 'Information Technology Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2024), University of Sydney, Australia' },
{ name: 'Yash Tembhurnikar', department: 'Information Technology Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2025), Purdue University' },
{ name: 'Pratiksha Kashid', department: 'Information Technology Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2025), UNSW Sydney' },
{ name: 'Divyank Panwar', department: 'Information Technology Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (2025-26, Pursuing), IIT Kanpur' },
{ name: 'Pooja Nemade', department: 'Information Technology Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MS (2025-26, Pursuing), Buffalo University' },
{ name: 'Trisha Navani', department: 'Information Technology Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (2025-26, Pursuing), PCCOE' },

{ name: 'Prathamesh Bacchav', department: 'Computer Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MBA (2025)' },
{ name: 'Sarthak Phulari', department: 'Computer Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (2025)' },
{ name: 'Makardhwaj Kamble', department: 'Computer Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (2025)' },
{ name: 'Ankita Anarase', department: 'Computer Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MS (2025)' },
{ name: 'Pranav Patil', department: 'Computer Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (2025)' },
{ name: 'Hardik Jain', department: 'Computer Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech (2024)' },
{ name: 'Kuldeep Lakhe', department: 'Computer Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech (2024)' },
{ name: 'Saee Chormunge', department: 'Computer Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech (2024)' },
{ name: 'Sharvari Kale', department: 'Computer Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2024)' },
{ name: 'Apeksha Mulimani', department: 'Computer Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2024)' },
{ name: 'Bhagyesha Patil', department: 'Computer Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2024)' },
{ name: 'Pratik Patik', department: 'Computer Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS (2024)' },
{ name: 'Mohit Gandhi', department: 'Computer Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS' },
{ name: 'Ashish Kulkarni', department: 'Computer Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'M.Tech' },
{ name: 'Sakshi Kshirsagar', department: 'Computer Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS' },
{ name: 'Niraj Sawant', department: 'Computer Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS' },
{ name: 'Vishal Pange', department: 'Computer Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS' },
{ name: 'Sumedh Joshi', department: 'Computer Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS' },
{ name: 'Yash Vibhute', department: 'Computer Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS' },

{ name: 'Anil Katte', department: 'Mechanical Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (Computational Mechanics), PCCoE, India' },
{ name: 'Pradnya Bhapkar', department: 'Mechanical Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (Computational Mechanics), PCCoE, India' },
{ name: 'Chaitanya Kulkarni', department: 'Mechanical Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (Aerospace Engineering), DIAT-DRDO, India' },
{ name: 'Parth Deshmukh', department: 'Mechanical Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (Mechanical Engineering), DIAT-DRDO, India' },
{ name: 'Aditya Kotwal', department: 'Mechanical Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (Thermal Engineering), IIT-Delhi, India' },
{ name: 'Ninad Acharya', department: 'Mechanical Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'M.Tech (Manufacturing Engineering), NIT-Warangal, India' },
{ name: 'MIHIR AMIT BHANSALI', department: 'Mechanical Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS Appl. Data Science, University of Florida, Florida' },
{ name: 'INGALE AVANTI SADASHIV', department: 'Mechanical Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MBA, DY Patil University Pune, India' },
{ name: 'SIDDHARTH DNYANESHWAR BANDAWANE', department: 'Mechanical Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'UG Researcher, University of Wisconsin-Madison' },
{ name: 'DAIVIK CHANDRABHAN BAVISKAR', department: 'Mechanical Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'Indian Maritime University Mumbai, India' },
{ name: 'DAMDHAR KAUSTUBH DEVIDAS', department: 'Mechanical Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'University of Mumbai, India' },
{ name: 'GOVIND MANOJKUMAR BAGDIYA', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'PGD-ERP, COEP, India' },
{ name: 'NISHIGANDHA GANESH DAREKAR', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS, Technische Universität Berlin, Germany' },
{ name: 'VARUN SHRIRAM GAWADE', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MIM, ESSEC Business School, France' },
{ name: 'VAISHNAV RAVINDRA KALDATE', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MEng, University of Massachusetts Amherst, USA' },
{ name: 'AKASH RAJESH MORE', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'PGDM, ISBS, Pune' },
{ name: 'SANKET RAJESH NAMPURKAR', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MSc, University of Manchester, England' },
{ name: 'TANISHQ VIJAYKUMAR PATIL', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "Master's" },
{ name: 'WAKE ADITYA SUNIL', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "Master's" },
{ name: 'ROHAN RAVINDRA KHARAT', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech, COEP, Pune' },
{ name: 'ADWAIT DEEPAK KULKARNI', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS in Robotics, Boston University, United States' },
{ name: 'ANUJA SUNIL RUPNAR', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS in Mech, Worcester Polytechnic Institute, Worcester, Massachusetts' },
{ name: 'OM VITTHALRAO SANGLE', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS in Mech and Process Engg., TU Bergakademie Freiberg, Germany' },
{ name: 'SONIYA RAMESH SHAH', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS in Engg. Mgt, Texas A&M University, United States' },
{ name: 'ROHIT RAJESH PAWAR', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'Master Degree, Aston University, England' },
{ name: 'ANIKET WAMAN DIDARE', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS in Science, Indian Institute of Technology, India' },
{ name: 'SHREEDHAR VIJAY LOHAR', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech in Mechatronics, COEP Technological University, India' },
{ name: 'NIMISH NITIN MAHADAR', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS, Arizona State University' },
{ name: 'JESWIN GIGI MATHEW', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'Master in Mech Engg., Technological University Dublin, Ireland' },
{ name: 'RAMAYANE SAURABH DEEPAK', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MBA, DY Patil Institute of Distance Learning, India' },
{ name: 'AAMOD VINAYAK PANDE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'ME in Robotics, Mechatronics and Automation, RMIT, Australia' },
{ name: 'AMEY RAVINDRA THONGE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'ME in Automotive Engineering, Technische Hochschule Ingolstadt, Germany' },
{ name: 'CHAITANYA DIGAMBAR KSHIRSAGAR', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Big Data Analytics, SunBeam Institute of Information Technology, India' },
{ name: 'TEJAS GULABRAO CHAVAN', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MBA in HRM & Services, SPPU, India' },
{ name: 'NACHIKET SAGAR DESHPANDE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'ME in Industrial Management, University of South California / USC Marshall School of Business, USA' },
{ name: 'PRAJWAL TRYAMBAKRAO DHOTE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MBA, K J Somaiya, India' },
{ name: 'PIYUSH JITESH GONAL', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Masters in Forecast and Technology Management, Technische Hochschule Ingolstadt, Germany' },
{ name: 'SAURABH MAHESH JADHAV', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Masters in Automotive Engineering, Technische Hochschule Ingolstadt, Germany' },
{ name: 'MALHAR RAHUL KHOLE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MTech Material Science and Technology, IIT Varanasi, India' },
{ name: 'MEHUL VINAYAK MANE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MTech in Designing, MIT-WPU, India' },
{ name: 'AKASH GIRISH GUGGARI', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'M.E. in Logistics, Materials and Supply Chains, Berlin School of Business & Innovation (BSBI), Germany' },
{ name: 'HARSHAL HARISCHANDRA MEHER', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MBA, IIM Lucknow, India' },
{ name: 'UMESH RAJSHEKHAR NANDARGI', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'ME Automotive System, Hochschule Esslingen - University of Applied Sciences, Germany' },
{ name: 'ATHARV RAJESH NIRHALI', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'ME Industrial Engineering, Northeastern University, USA' },
{ name: 'OJAS JAIPRAKASH VISHWAKARMA', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'M.S. Renewable Energy System, Hamburg University of Applied Sciences, Germany' },
{ name: 'PRANITA UMESH PACHKAWADE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS Sustainable Energy System, University of Freiburg, Germany' },
{ name: 'AKANKSHA PRAKASH PAWAR', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS Engineering and Management, Technische Hochschule Ingolstadt, Germany' },
{ name: 'TUSHAR BADRINATH RANE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MBA Operations Management and Supervision, NMIMS CDOE, India' },
{ name: 'RUTURAJ PRASHANT YAWALE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'ME International Automotive Engineering, Technische Hochschule Ingolstadt, Germany' },
{ name: 'SAKSHI GANESH SHENDE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS in Mechanical Engineering, New York University, USA' },
{ name: 'SAURABH SURYAKANT NAGENDRA', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MTech in Computer Integrated Manufacturing, NIT Warangal, India' },
{ name: 'HRISHIKESH SUHAS SHINTRE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Business Administration (General), Sydenham Institute of Management Studies, India' },
{ name: 'SHREYASH SHRIKANT KULKARNI', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Masters in Logistics Management and Supply Chain, University of Warwick, England' },
{ name: 'PRANAV TUKARAM TATHE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MBA, IIM Calcutta, India' },
{ name: 'DIGVIJAY CHANDRASEN THAKARE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Machine Design, IIT Guwahati, India' },
{ name: 'PRAJWAL VIJAY THORAT', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Electric Vehicles, MIT ADT, India' },
{ name: 'URVESH VIKHIAT BERRY', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Business Management, London Business School, England' },
{ name: 'TANMAY RAJESH VINCHAVEKAR', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Management Studies, Jamnalal Institute of Management Studies, India' },
{ name: 'RUGVED SHARADRAO WANKHADE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Marketing Management, Indira School of Business Studies PGDM, India' },
{ name: 'PRATHAMESH PRALHAD PAWAR', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Management, IIT Kanpur, India' },
{ name: 'NIKHIL CHHOTU SOMWANSHI', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Management & Business Analytics, IISc, India' },
{ name: 'RANBIRSINGH MANMITSINGH SAINI', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Engineering Management, University of Leicester, England' },
{ name: 'ADITYA PRAMOD PALANDE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Industrial Engineering, Penn State University, United States' },
{ name: 'ADITYA RAVI JADHAV', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Management, ESCP Business School, Germany/Spain' },
{ name: 'ATHARVA AJAY DESHPANDE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Mechanical Engineering, New York University, United States' },
{ name: 'PRATIK JANARDAN AVHAD', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Mechanical Engineering, Pimpri Chinchwad College of Engineering, India' },
{ name: 'ATHARVA RAVINDRA BHORPE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Mechatronics, Robotics and Automation, RWTH Aachen University, Germany' },
{ name: 'PRANAV PRADIP CHANDUGADE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Supply Chain Management, SRH University, Germany' },
{ name: 'SOHAM SHRISH KHARKAR', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Computer Aided Mechanical Engineering, RWTH Aachen University, Germany' },
{ name: 'PRANAV PRASHANT DAHIWADE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Management, Frankfurt School of Finance and Management, Germany' },
{ name: 'ANJALI SANJAY RAUT', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Supply Chain and Logistics Management, University of Warwick, England' },
{ name: 'SIDDHARTH VINAYAK SHROTRI', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Mechatronics, Automation and Robotics, Worcester Polytechnic Institute, USA' },
{ name: 'SUVID SANJAY SHINDE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Robotic Systems Engineer, RWTH Aachen University, Germany' },
{ name: 'AMEY PRAVIN TALEGAONKAR', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Management, Imperial College Business School, England' },
{ name: 'VAISHNAVI BHALCHANDRA KASAR', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Industrial Engineering, North Carolina State University, United States' },
{ name: 'HRITIKA SANJAY WAGHJALE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Industrial Engineering, Penn State University, United States' },
{ name: 'GANESH ABHAY BHARAMBE', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Business Administration, Department of Management Science (PUMBA), India' },
{ name: 'RITESH LALU PATIL', department: 'Mechanical Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M Tech in Nuclear Science and Engineering, Homi Bhabha National Institute of Technology' },
{ name: 'Ms. SHUBHADA SANTOSH PADWAL', department: 'Mechanical Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MS in Management, Technical University of Munich' },
{ name: 'Yash Naseri', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MBA/PGDM in International Business/General Management Development Institute (MDI) Gurgaon ' },
{ name: 'Mridhul Iyer', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS in Quantitative Economics, Indian Statistical Institute, Kolkata ' },
{ name: 'Om Anant Kulkarni', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'Master of Science (M.S) in Aerospace Technical University of Munich (TUM), Germany' },
{ name: 'Yash Nitin Patil', department: 'Mechanical Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'Masters in Engineering Management ,Duke University ' },
{ name: 'Yash Nitin Patil', department: 'Mechanical Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'M.Tech in Mobility Engineering ,Indian Institute of Science(IISc) Bangalore' },

{ name: 'Miss. Vijaya Ghatol', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MBA in Sustainable Energy Management (2025–26), NICMAR, Pune, India' },
{ name: 'Ganesh Kodnani', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MBA in Advanced Construction Management (2025–26), NICMAR, Pune, India' },
{ name: 'Manas Tendulkar', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MBA in Advanced Construction Management (2025–26), NICMAR, Pune, India' },
{ name: 'Tejas Solunke', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MBA in Advanced Construction Management (2025–26), NICMAR, Pune, India' },
{ name: 'Gurkiratsingh Arora', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MTech in Computer Aided Structural Engineering (2025–26), IIIT Hyderabad, India' },
{ name: 'Devesh Patil', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MSc in Construction Management (2025–26), University of Birmingham, Dubai' },
{ name: 'Vaishnavi Patil', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MTech in Town Planning (2025–26), COEP Technical University, Pune, India' },
{ name: 'Onkar Kusmade', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MTech in Structures (2025–26), IIT Madras, India' },
{ name: 'Varun Desai', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MS in Building Construction and Facilities Management (2025–26), Georgia Tech, Atlanta' },
{ name: 'Aditya Tatiya', department: 'Civil Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: 'MS in Master of Business Analytics (2025–26), University of Technology Sydney' },
{ name: 'Harsh Gangwal', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS in Construction Management (2024–25), Texas A&M University, USA' },
{ name: 'Milind Patil', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MTech in Transportation Engineering (2024–25), COEP Technical University, Pune, India' },
{ name: 'Dhwani Ramawat', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MTech in Professional Project Management (2024–25), IIT Delhi, India' },
{ name: 'Shraddhesh Shirode', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MTech in Structural Engineering (2024–25), K. K. Wagh, Nashik, India' },
{ name: 'Apurva Suryawanshi', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management (2024–25), NICMAR, Pune, India' },
{ name: 'Ishika Suryawanshi', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management (2024–25), NICMAR, Pune, India' },
{ name: 'Raj Peswani', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS in Analytics (2024–25), UC Berkeley, USA' },
{ name: 'Bhavesh Mahajan', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management (2024–25), VJTI Mumbai, India' },
{ name: 'Nishant Kad', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management (2024–25), COEP Technical University, Pune, India' },
{ name: 'Vishal Lad', department: 'Civil Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management (2024–25), COEP Technical University, Pune, India' },
{ name: 'Pratham Agarwal', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MBA in Advanced Construction Management (2023–24), NICMAR, Pune, India' },
{ name: 'Purvesh Bhole', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'ME in Structural Engineering (2023–24), Pravara Rural College of Engineering, Loni, India' },
{ name: 'Prathamesh Gurav', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS in Structural Engineering (2023–24), Texas A&M University, USA' },
{ name: 'Pushpak Joshi', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech in Structural Engineering (2023–24), Sardar Patel College of Engineering, Mumbai, India' },
{ name: 'Mansi Lonkar', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MBA in General Management (2023–24), IIT Kanpur, India' },
{ name: 'Kartik Waghere', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS in Construction Management (2023–24), University of Illinois, USA' },
{ name: 'Isha Mali', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech in Structural Engineering (2023–24), COEP Technical University, Pune, India' },
{ name: 'Kartik Patil', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MS in Construction Management (2023–24), Texas A&M University, USA' },
{ name: 'Akshada Reur', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech in Environment and Water Resources Engineering (2023–24), COEP Technical University, Pune, India' },
{ name: 'Rutuja Patil', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech in Transportation Engineering (2023–24), COEP Technical University, Pune, India' },
{ name: 'Prachi Pawar', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Engineering and Management (2023–24), MIT WPU, Pune, India' },
{ name: 'Himanshu Thakur', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech in Structural Engineering (2023–24), MIT WPU, Pune, India' },
{ name: 'Harshavardhan Rathod', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech in Environmental Engineering (2023–24), Pune, India' },
{ name: 'Lalit Pandit', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech in Environmental Engineering (2023–24), Pune, India' },
{ name: 'Harshal Mali', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management (2023–24), Sandeep University, Nashik, India' },
{ name: 'Kaustubh Anchawale', department: 'Civil Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management (2023–24), Government College of Engineering, Karad, India' },
{ name: 'Sumedh Aher', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MTech in Structures (2022–23), BITS Hyderabad, India' },
{ name: 'Sawani Anwale', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MBA in HR Analytics (2022–23), XIME, India' },
{ name: 'Manjitsingh Girase', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MTech in Transportation Engineering (2022–23), IIT Powai Mumbai, India' },
{ name: 'Suyash Khemnar', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS in Construction Management (2022–23), Duke University, USA' },
{ name: 'Saurabh Patil', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS in Environmental Engineering & Pollution Control (2022–23), Griffith University, Australia' },
{ name: 'Aditya Sali', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MBA in Marketing (2022–23), SIBM Pune, India' },
{ name: 'Bhakti Kapse', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS (2022–23), University of California, Berkeley, USA' },
{ name: 'Raj Kene', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS (2022–23), University of California Riverside, USA' },
{ name: 'Tanmay Kadu', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS (2022–23), New York University, USA' },
{ name: 'Sayali Pawar', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS (2022–23), Purdue University, USA' },
{ name: 'Vedangi Patil', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MS in Structural Engineering (2022–23), Texas A&M University, USA' },
{ name: 'Pooja Jat', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MTech in Structural Engineering (2022–23), MIT WPU, Pune, India' },
{ name: 'Swaraj Hanmante', department: 'Civil Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: 'MSc in International Business and Strategy (2022–23), Lancaster University, UK' },
{ name: 'Gavhane Tushar Haribhau', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'ME (2021–22), AISSMS, Pune, India' },
{ name: 'Jagdhane Suraj Dhananjay', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'MS (2021–22), University of Texas at Arlington, USA' },
{ name: 'Karle Aishwarya Ramesh', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'ME in Structures (2021–22), JSPM, Pune, India' },
{ name: 'Poossery Pooja', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'ACM (2021–22), NICMAR, Pune, India' },
{ name: 'Shende Asha', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'MTech (2021–22), NIT Durgapur, India' },
{ name: 'Gaikwad Renuka', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'MTech (2021–22), COEP, Pune, India' },
{ name: 'Pophale Mrunal', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'MTech (2021–22), COEP, Pune, India' },
{ name: 'Hrutuja Chaudhari', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'MS in Energy Water Sustainable Technology (2021–22), Illinois University, USA' },
{ name: 'Sumedh Kharat', department: 'Civil Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: 'MS in Construction Management (2021–22), Purdue University, USA' },
{ name: 'Shinde Vaishnavi', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'MBA in Advanced Construction Management (2020–21), NICMAR, Pune, India' },
{ name: 'Viraj Bhandari', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'MS in Construction Management and Technology (2020–21), Arizona State University, USA' },
{ name: 'Shelke Ashwinkumar', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'ME in Structural Engineering (2020–21), PDVVP College of Engineering, Ahmednagar, India' },
{ name: 'Bajbalkar Mayuresh', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'MTech (2020–21), MIT-ADT University, Pune, India' },
{ name: 'Sonawane Hrushikesh', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'Higher Studies (2020–21), International Institute of Management and Science' },
{ name: 'Kalhapure Amruta', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'Post Graduation Program in Advanced Construction Management (2020–21), NICMAR, Pune, India' },
{ name: 'Sathone Manthan', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'Post Graduation Program in Advanced Construction Management (2020–21), NICMAR, Pune, India' },
{ name: 'More Ashwini', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'ME in Construction Technology and Management (2020–21), SGCOE&T Bhusawal, India' },
{ name: 'Chaitanya Chudiwal', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'MS (2020–21), University of Texas at Arlington, USA' },
{ name: 'Bhushan Bhavsar', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'Post Graduation Program in Advanced Construction Management (2020–21), NICMAR, Pune, India' },
{ name: 'Rohan Patil', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'Post Graduation Program in Advanced Construction Management (2020–21), NICMAR, Pune, India' },
{ name: 'Shubham Paymal', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'MTech in Structures (2020–21), MIT-WPU, Pune, India' },
{ name: 'Hitesh Patil', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'MS in Construction Management and Technology (2020–21), Arizona State University, USA' },
{ name: 'Rohit Datir', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'MS in Project Management (2020–21), Northeastern University, Boston, USA' },
{ name: 'Prajwal Nale', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'Post Graduation Program in Advanced Construction Management, NICMAR, Pune, India' },
{ name: 'Rohit Deokar', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'MTech in Construction and Management, MIT-WPU, Pune, India' },
{ name: 'Omkar Patil', department: 'Civil Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management, Sardar Patel College of Engineering, Mumbai, India' },
{ name: 'Kolge Ankit', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'Post Graduation Program in Advanced Construction Management, NICMAR, Pune, India' },
{ name: 'Yogita Patel', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MS in Water Science and Engineering, Karlsruhe Institute of Technology, Germany' },
{ name: 'Suraj Dabhade', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'Post Graduation Program in Quantity Survey and Contract Management, NICMAR, Pune, India' },
{ name: 'Gaikwad Manasi', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MS in Project Management, Northeastern University, Boston, USA' },
{ name: 'Sushant More', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MS in Transportation Engineering, Northeastern University, Boston, USA' },
{ name: 'Dipti More', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MS in Project Management, Northeastern University, Boston, USA' },
{ name: 'Deepali Tondare', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MS in Construction Management, Texas A&M University, USA' },
{ name: 'Shubham Bhadhane', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MS in Construction Management and Technology, Arizona State University, USA' },
{ name: 'Shubham Katore', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MS in Project Engineering and Management, NICMAR, Pune, India' },
{ name: 'Kunal Patil', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MS in Project Engineering and Management, NICMAR, Pune, India' },
{ name: 'Mayur Salunke', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MS in Information Studies, Texas A&M University, USA' },
{ name: 'Shriya Jadhav', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management, Sardar Patel College of Engineering, Mumbai, India' },
{ name: 'Aditya Sangle', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'PGDM, JAGSOM, Bangalore, India' },
{ name: 'Akshaykumar Shinde', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management, Government College of Engineering, Karad, India' },
{ name: 'Adhav Ankit', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MTech in Structural Engineering, College of Engineering, Pune, India' },
{ name: 'Bansode Pradnya', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management, Government College of Engineering, Karad, India' },
{ name: 'Basarkar Shubham', department: 'Civil Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: 'MTech in Structural Engineering, VNIT Nagpur, India' },
{ name: 'Pore Tanvi Satish', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'MTech, VJTI Mumbai, India' },
{ name: 'Udhane Darshana Hemant', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'MS, Deakin University, Australia' },
{ name: 'Bedmutha Saurabh Nitin', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'MS, University of New South Wales, Australia' },
{ name: 'Mankhair Roshan Vilasrao', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'Higher Studies, IIT Powai Mumbai, India' },
{ name: 'Tapas Mahesh Ramesh', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'MS, East Carolina University, Greenville, USA' },
{ name: 'Roge Kartik Shantaram', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'MS, Deakin University, Australia' },
{ name: 'Malwade Aniket Prashant', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'MS, Deakin University, Australia' },
{ name: 'Kolte Rushikesh Rajesh', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'MS, MNIT Jaipur, India' },
{ name: 'Kadam Abhishek Dilip', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'Higher Studies, D Y Patil COE Akurdi, Pune, India' },
{ name: 'Karhadkar Shantanu C.', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'Higher Studies, RWTH Aachen University, Germany' },
{ name: 'Nerkar Monali Jyotiram', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'MTech, Government College of Engineering, Karad, India' },
{ name: 'Vinay Agarwal', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'MTech, NIT Warangal, India' },
{ name: 'Shubham Pawar', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'Higher Studies, Imperial College of Engineering and Research, India' },
{ name: 'Dhanbar Aditya', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'Higher Studies, Imperial College of Engineering and Research, India' },
{ name: 'Kunal Badhane', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'MS, Sandip University, India' },
{ name: 'Sachin Bhure', department: 'Civil Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: 'MTech, Imperial College of Engineering and Research, India' },
{ name: 'Harshal Rasal', department: 'Civil Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'MTech in Hydraulics and Water Resources Engineering, IIT Kharagpur, India' },
{ name: 'Ganesh Petkar', department: 'Civil Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'MTech in Transportation Engineering, VNIT Nagpur, India' },
{ name: 'Nilay Warkhedkar', department: 'Civil Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'MS in Environmental Engineering' },
{ name: 'Tejaswini Mankar', department: 'Civil Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'MTech in Environmental Engineering, D Y Patil College of Engineering, Akurdi, India' },
{ name: 'Pawan Chagedia', department: 'Civil Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'MTech in Structural Engineering, NIT Hamirpur, India' },
{ name: 'Mahesh Jamdade', department: 'Civil Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'Higher Studies, NICMAR, Pune, India' },
{ name: 'Allen Gilbert', department: 'Civil Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'MS in Project Management, De Montfort University, Leicester, UK' },
{ name: 'Ambaresh Tejari', department: 'Civil Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'MS' },
{ name: 'Shashank Kadu', department: 'Civil Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: 'Post Graduation Program in Project Engineering Management, NICMAR, Pune, India' },
{ name: 'Parag Mahajan', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'MTech in Water Resources Engineering, Government College of Engineering, Aurangabad, India' },
{ name: 'Juzer Shaikh', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'Post Doc / PhD / MTech in Earth Sciences, Indian Institute of Science, Bangalore, India' },
{ name: 'Rushikesh Kasar', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management' },
{ name: 'Bhagyarekha Jadhav', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'MTech in Water Resources Engineering, Government College of Engineering, Aurangabad, India' },
{ name: 'Abhishek Mahajan', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management, VJTI Mumbai, India' },
{ name: 'Akshay Bagal', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management, D Y Patil Ambi, Talegaon, India' },
{ name: 'Bhushan Malusare', department: 'Civil Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: 'MTech in Construction Management, D Y Patil Ambi, Talegaon, India' },

{ name: 'Arin Ashish Jain', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech Micro Electronics and VLSI Design (2025-2027), National Institute of Technology Calicut, India' },
{ name: 'Shreya Rajendra Desai', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.S. in Embedded System, Chemnitz Technical University, Germany' },
{ name: 'Janhavi Chati', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MSc Electronics Engineering, University of Southampton, England' },
{ name: 'Pradnya Rajendra Deore', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MBA General Management (2025-2027), Indian Institute of Management Visakhapatnam, India' },
{ name: 'Mohammad Bohra', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech Micro Electronics and VLSI Design (Solid State Devices) (2025-2027), IIT Bombay, India' },
{ name: 'Onkar Tukaram Bobade', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'M.Tech Microelectronics and VLSI (2026-2028), IIT Hyderabad, India' },
{ name: 'Soumitya Sanjay Patil', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: 'MS Infotech (Embedded Systems) (2026-2028), University of Stuttgart, Germany' },
{ name: 'Nilkanth Kadlag', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "Master’s of Science Computer Science (August 2023 - July 2025), University of Georgia, United States of America" },
{ name: 'Sandeep Sharma', department: 'Electronics and Telecommunication Engineering', year: '2008', photo: 'images/default-avatar.jpg', description: "MS ECE (Electrical and Computer Engineering), Missouri University of Science and Technology" },
{ name: 'Jaydeep Ananda Mohite', department: 'Electronics and Telecommunication Engineering', year: '2010', photo: 'images/default-avatar.jpg', description: "M.Tech Electronics Engineering, Walchand College of Engineering Sangli" },
{ name: 'Dr. Mane Harshali Dnyaneshwar', department: 'Electronics and Telecommunication Engineering', year: '2011', photo: 'images/default-avatar.jpg', description: "PhD Signal Processing, K L University" },
{ name: 'Jaywant Kamble', department: 'Electronics and Telecommunication Engineering', year: '2013', photo: 'images/default-avatar.jpg', description: "ME VLSI and Embedded Systems, Pune University" },
{ name: 'Sailee Borse', department: 'Electronics and Telecommunication Engineering', year: '2016', photo: 'images/default-avatar.jpg', description: "MBA General, Indian Institute of Management Kozhikode" },
{ name: 'Shreekanya Kodate', department: 'Electronics and Telecommunication Engineering', year: '2017', photo: 'images/default-avatar.jpg', description: "M.Tech Communication Engineering, Indian Institute of Technology Bombay" },
{ name: 'Shalvraj Dhananjay Kulkarni', department: 'Electronics and Telecommunication Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: "M.Tech Automotive Electronics, VIT Vellore (University Gold Medalist)" },
{ name: 'Siddhi Gaikwad', department: 'Electronics and Telecommunication Engineering', year: '2018', photo: 'images/default-avatar.jpg', description: "M.Sc. Electronic Information Engineering, Trinity College Dublin" },
{ name: 'Mahesh Balasaheb Raut', department: 'Electronics and Telecommunication Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: "Masters Data Science, University of Guelph" },
{ name: 'Antara Deepak Muley', department: 'Electronics and Telecommunication Engineering', year: '2019', photo: 'images/default-avatar.jpg', description: "MS Electrical and Computer Engineering, Michigan Technological University" },
{ name: 'Harshit Sampgaon', department: 'Electronics and Telecommunication Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: "MS Electrical and Computer Engineering - Machine Learning, Northeastern University" },
{ name: 'Snehal Patil', department: 'Electronics and Telecommunication Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: "MS Electrical Engineering, California State University Fullerton" },
{ name: 'Gaurree Lohiya', department: 'Electronics and Telecommunication Engineering', year: '2020', photo: 'images/default-avatar.jpg', description: "MS Engineering Management, University of Illinois at Urbana Champaign" },
{ name: 'Nikhil Samir Bhosale', department: 'Electronics and Telecommunication Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: "MS Data Science and Analytics, Illinois Institute of Technology" },
{ name: 'Raviraj Mahadeo Khopade', department: 'Electronics and Telecommunication Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: "MS Computer Science, Illinois Institute of Technology" },
{ name: 'Aniket Chopade', department: 'Electronics and Telecommunication Engineering', year: '2021', photo: 'images/default-avatar.jpg', description: "MS Computer Engineering, San Jose State University" },
{ name: 'Akash Rajesh Biyani', department: 'Electronics and Telecommunication Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: "MSc Embedded Computing System, University of Southampton & RPTU Kaiserslautern" },
{ name: 'Shounak Rajendra Powar', department: 'Electronics and Telecommunication Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: "MS Computer Science, Iowa State University" },
{ name: 'Shashank Tiwari', department: 'Electronics and Telecommunication Engineering', year: '2022', photo: 'images/default-avatar.jpg', description: "MBA Human Resource Management, XLRI Jamshedpur" },
{ name: 'Utkarsha Vikas Chinchore', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "MS Mechatronics, KTH Royal Institute of Technology Sweden" },
{ name: 'Jaiee Anand Bhange', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "Master of Information Technology - Artificial Intelligence, University of New South Wales Sydney" },
{ name: 'Chirag Ramesh Kharche', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "MS Electrical Engineering - Power Electronics, Virginia Tech" },
{ name: 'Tushar Subhash Alase', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "MS Electrical & Computer Engineering, Purdue University" },
{ name: 'Shubham Rajesh Kumar Das', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "Ph.D. Theoretical Physics, The Institute of Mathematical Sciences (IMSc)" },
{ name: 'Gargi Patel', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "Master of Design (M.Des) User Experience Design (UX), MIT Institute of Design (MIT ID)" },
{ name: 'Anuj Kiran Bhole', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: "MS Computer Science, University of Sydney" },
{ name: 'Rishabh Sharma', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: "ME Electrical Engineering and Embedded Systems, Ravensburg Weingarten University of Applied Sciences" },
{ name: 'Ruchita Pame', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: "Applied for MS Data Science, UC Boulder & Texas A&M" },
{ name: 'Yash Rajesh Meshram', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: "Higher Studies Information Not Available" },
{ name: 'Nandini Suresh Sharma', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: "MS Engineering Management, California State University East Bay" },
{ name: 'Aditi Yogesh Vaidya', department: 'Electronics and Telecommunication Engineering', year: '2024', photo: 'images/default-avatar.jpg', description: "MS Engineering Management, California State University" },
{ name: 'Shreya Desai', department: 'Electronics and Telecommunication Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: "MS Embedded Systems, Technische Universität Chemnitz, Germany" },
{ name: 'Vibhav Jagdish Dalvi', department: 'Electronics and Telecommunication Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: "MS Engineering Management, Northeastern University" },
{ name: 'Tushar Sadanand Alande', department: 'Electronics and Telecommunication Engineering', year: '2025', photo: 'images/default-avatar.jpg', description: "M.Tech Automotive Electronics, Vellore Institute of Technology Vellore" },
{ name: 'Parth Jayant More', department: 'Electronics and Telecommunication Engineering', year: '2023', photo: 'images/default-avatar.jpg', description: "MS Internet of Things, Northeastern University" },
];
