const distinguishedAlumni = [
    { name: 'Gaurav Mahale', department: 'Computer Engineering REGIONAL', year: '2025', educationType: 'MS', achievement: 'Pursuing MS (Data Science)\nILETS', photo: 'images/Gaurav Mahale.png' },

    { name: 'Ajinkya Waghulde', department: 'Information Technology (IT)', year: '2009', educationType: 'MS', achievement: 'MS Computer Science \nUniversity of Southern California', photo: 'images/Ajinkya Waghulde.png' },
    { name: 'Rhuta Joshi', department: 'Information Technology (IT)', year: '2019', educationType: 'MS', achievement: 'MS – Computer Graphics and Gaming Technology University of Pennsylvania', photo: 'images/Rhuta Joshi.png' },
    { name: 'Mr Abhishek Barane', department: 'Information Technology (IT)', year: '2022', educationType: 'M.Tech', achievement: 'M.Tech. IIT Mumbai', photo: 'images/Mr Abhishek Barane.png' },
    { name: 'Nupur Kulkarni', department: 'Information Technology (IT)', year: '2022', educationType: 'MS', achievement: 'MS Computer Science \nSaarland University, Germany', photo: 'images/Nupur Kulkarni.png' },
    { name: 'Janet Jocob', department: 'Information Technology (IT)', year: '2020', educationType: 'M.des', achievement: 'National Institute of Design(NID), Banglore', photo: 'images/Janet Jocob.png' },
    

    { name: 'Mr. Swijal Patil', department: 'Computer Engineering', year: '2012', educationType: 'MS', achievement: 'Master in Computer Science at Stony Brook University, Currently Software Development Engineer at Amazon.com', photo: 'images/Mr. Swijal Patil.png' },
    { name: 'Ms. Aishwarya Sureban', department: 'Computer Engineering', year: '2017', educationType: 'MS', achievement: 'Completed MS from Illunois Institute of Technology, USA and currently working as a Software Developer at Amazon, USA.', photo: 'images/Ms. Aishwarya Sureban.png' },
    { name: 'Mr. Ankush Pathak', department: 'Computer Engineering', year: '2018', educationType: 'MS', achievement: 'Completed MS from Indiana University Bloomington, USA and currently working as a Software Developer at Canonical (Ubuntu)', photo: 'images/Mr. Ankush Pathak.png' },
    { name: 'Mr. Ravindra More', department: 'Computer Engineering', year: '2016', educationType: 'UPSC', achievement: ' serving as Lieutenant along Tawang Axis in Arunachal Pradesh.', photo: 'images/Mr. Ravindra More.png' },
    { name: 'Mr. Birudev Khandekar', department: 'Computer Engineering', year: '2014', educationType: 'MPSC', achievement: 'Working as a PSI in Maharashtra Police from 2021 MPSC Batch.', photo: 'images/Mr. Birudev Khandekar.png' },
    
    { name: 'Shubhada Padwal', department: 'Mechanical Engineering', year: '2019', educationType: 'MS', achievement: 'Masters in Management\nTechnical University of Munich, Germany', photo: 'images/Shubhada Padwal.png' },
    { name: 'Om Anant Kulkarni', department: 'Mechanical Engineering', year: '2023', educationType: 'M.Sc', achievement: 'M.Sc. Aerospace Engineering\nTechnical University of Munich, Germany', photo: 'images/Om Anant Kulkarni.png' },
    { name: 'Mridhul K. Iyer', department: 'Mechanical Engineering', year: '2023', educationType: 'MS', achievement: 'M.S. Quantitative Economics\nIndian Statistical Institute, Kolkata', photo: 'images/Mridhul K. Iyer.png' },
    { name: 'Yash Naseri', department: 'Mechanical Engineering', year: '2023', educationType: 'MBA', achievement: 'MiM/MBA Dual Degree International Business\nManagement Development Institute (MDI) Gurgaon/ESCP Business School Paris', photo: 'images/Yash Naseri.png' },
    { name: 'Shivam Hake', department: 'Mechanical Engineering', year: '2023', educationType: 'M.Tech', achievement: 'M.Tech in Mobility Engineering\nIndian Institute of Science, Bangalore.', photo: 'images/Shivam Hake.png' },
    { name: 'Lakhan Ashok Patil', department: 'Mechanical Engineering', year: '2012', educationType: 'MGSTD', achievement: 'State Tax Inspector(STI) at Maharashtra State GST Department ', photo: 'images/Lakhan Ashok Patil.png' },
    { name: 'Ajay Bhujbal', department: 'Mechanical Engineering', year: '2018', educationType: 'ISRO', achievement: 'ISRO Scientist SC (Group A Gazetted Post)', photo: 'images/Ajay Bhujbal.png' },
    { name: 'Nitin Shinde', department: 'Mechanical Engineering', year: '2019', educationType: 'GATE', achievement: 'Engineering Assistant at ONGC Mumbai', photo: 'images/Nitin Shinde.png' },
    { name: 'Ritesh Lalu Patil', department: 'Mechanical Engineering', year: '2024', educationType: 'BARC', achievement: 'Scientific Officer at BARC', photo: 'images/Ritesh Lalu Patil.png' },

    { name: 'Vanshaj Wadhwa', department: 'Civil Engineering', year: '2016', educationType: 'UPSC', achievement: 'Major, Indian Army\nUPSC-CDS', photo: 'images/Vanshaj Wadhwa.png' },
    { name: 'Vikash Kumar Sharma', department: 'Civil Engineering', year: '2016', educationType: 'UPSC', achievement: 'Major, Indian Army\nUPSC-CDS', photo: 'images/Vikash Kumar Sharma.png' },
    { name: 'Shivam Bondre', department: 'Civil Engineering', year: '2022', educationType: 'UPSC', achievement: 'Major, Indian Army\nUPSC-CDS', photo: 'images/Shivam Bondre.png' },
    { name: 'Dhananjay Gaonkar', department: 'Civil Engineering', year: '2020', educationType: 'MPSC', achievement: 'Assistant Executive Engineer,\n Water Resources Department\nMPSC-MES 2021 (State Rank 1)', photo: 'images/Dhananjay Gaonkar.png' },
    { name: 'Sudarshan Yadav', department: 'Civil Engineering', year: '2022', educationType: 'MPSC', achievement: 'Sub Divisional Officer,\nSoil and Water Conservation\nDepartment', photo: 'images/Sudarshan Yadav.png' },
    { name: 'Prathamesh Solapure', department: 'Civil Engineering', year: '2020', educationType: 'GATE', achievement: 'Sr. Operations Officer,\nHindustan petroleum corporation limited', photo: 'images/Prathamesh Solapure.png' },
    { name: 'Viraj Bhandari', department: 'Civil Engineering', year: '2020', educationType: 'MS', achievement: 'MS (Construction Management) Arizona State University', photo: 'images/Viraj Bhandari.png' },
    { name: 'Mahesh Tapas', department: 'Civil Engineering', year: '2017', educationType: 'M.Tech', achievement: 'Post Doctoral Researcher,Ohio State University, Columbus Ohio, United States, PhD Integrated Coastal Sciences, East Carolina University, MTech Water Resources Engineering, NIT Warangal', photo: 'images/Mahesh Tapas.png' },
    { name: 'Shende Asha', department: 'Civil Engineering', year: '2021', educationType: 'M.Tech', achievement: 'PhD Scholar, Civil Engineering (Environmental Engineering),    IIT Hyderabad , MTech Environmental Science and Technology, NIT, Durgapur', photo: 'images/Shende Asha.png' },
    { name: 'Zijer haikh', department: 'Civil Engineering', year: '2016', educationType: 'M.Tech', achievement: 'Postdoctoral Associate at the University of Minnesota, PhD and MTech Earth Sciences Indian Institute of Science, Bengaluru', photo: 'images/Zijer haikh.png' },
    { name: 'Vedangi Patil', department: 'Civil Engineering', year: '2021', educationType: 'MS', achievement: 'MS (Structural Engineering) TEXAS A&M University', photo: 'images/Vedangi Patil.png' },
    { name: 'Roshan Mankhair', department: 'Civil Engineering', year: '2020', educationType: 'M.Tech', achievement: 'PhD and  MTech in Environmental Science and Engineering\nIIT, Bombay', photo: 'images/Roshan Mankhair.png' },
    { name: 'Parag Mahajan', department: 'Civil Engineering', year: '2016', educationType: 'M.Tech', achievement: 'MTech, Water Resources Engineering,\nGovt. College of Engineering, Aurangabad', photo: 'images/Parag Mahajan.png' },
    { name: 'Harshal Rasal', department: 'Civil Engineering', year: '2017', educationType: 'M.Tech', achievement: 'MTech, Hydraulics and Water Resources Engineering,\nIIT, Kharagpur', photo: 'images/Harshal Rasal.png' },
    { name: 'Manasi Lonkar', department: 'Civil Engineering', year: '2023', educationType: 'MBA', achievement: 'MBA, Department of Management Sciences, \nIIT Kanpur, General Management', photo: 'images/Manasi Lonkar.png' },
    { name: 'Rohit Datir', department: 'Civil Engineering', year: '2020', educationType: 'MS', achievement: 'MS in Project management,\nNortheastern University, Boston', photo: 'images/Rohit Datir.png' },
    { name: 'Vinay Agarwal', department: 'Civil Engineering', year: '2018', educationType: 'M.Tech', achievement: 'M Tech in Remote Sensing and GIS,\nNIT Warangal', photo: 'images/Vinay Agarwal.png' },
    { name: 'Darshana Udhane', department: 'Civil Engineering', year: '2018', educationType: 'MS', achievement: 'MS in Construction Management,\nDeakin University, Australia', photo: 'images/Darshana Udhane.png' },

    { name: 'Rahul Randive', department: 'Civil Engineering', year: '2016', educationType: 'MES', achievement: 'Urban development department municipal Engineer ', photo: 'images/Rahul Randive.png' },
    { name: 'Kamalesh Zinjurke', department: 'Civil Engineering', year: '2016', educationType: 'MES', achievement: 'Assistant Engineer-Grade2 Water Resources Department, GoM', photo: 'images/Kamalesh Zinjurke.png' },
    { name: 'Avinash Bogulwar', department: 'Civil Engineering', year: '2016', educationType: 'MES', achievement: 'Water Conservation Officer, WCD, GoM ', photo: 'images/Avinash Bogulwar.png' },
    { name: 'Bhagyarekha Jadhav', department: 'Civil Engineering', year: '2016', educationType: 'MES', achievement: 'Assistant Engineer-Class II\nMAHATRANSCO\n', photo: 'images/Bhagyarekha Jadhav.png' },
    { name: 'Rushikesh Kasar', department: 'Civil Engineering', year: '2016', educationType: 'MES', achievement: 'Sectional Engineer, PWD, GoM \n', photo: 'images/Rushikesh Kasar.png' },
    { name: 'Rajneesh Baria', department: 'Civil Engineering', year: '2016', educationType: 'MES', achievement: 'Junior Engineer ,Water Resources Department, GoM', photo: 'images/Rajneesh Baria.png' },
    { name: 'Tejaswini Bagul', department: 'Civil Engineering', year: '2016', educationType: 'MES', achievement: 'Junior Engineer, Water supply Department, Pune Municipal Corporation, GoM', photo: 'images/Tejaswini Bagul.png' },
    { name: 'Yogesh Sharma', department: 'Civil Engineering', year: '2016', educationType: 'MES', achievement: 'Sectional Engineer, \nPWD, GoM', photo: 'images/Yogesh Sharma.png' },


    { name: 'Nachiket shelke', department: 'Electronics and Telecommunication Engineering', year: '2014', educationType: 'UPSC', achievement: 'UPSC AIR-167', photo: 'images/Nachiket shelke.png' },
    { name: 'Harshal Patil', department: 'Electronics and Telecommunication Engineering', year: '2014', educationType: 'UPSC', achievement: 'UPSC AIR-833', photo: 'images/Harshal Patil.png' },
    { name: 'Mane Harshali Dnyaneshwar', department: 'Electronics and Telecommunication Engineering', year: '2011', educationType: 'M.Tech', achievement: 'K L University,Visakhapatnam', photo: 'images/Mane Harshali Dnyaneshwar.png' },
    { name: 'Sailee Borse', department: 'Electronics and Telecommunication Engineering', year: '2016', educationType: 'MBA', achievement: 'MBA Indian Institute of Management Kozhikode', photo: 'images/Sailee Borse.png' },
    { name: 'Shreekanya Kodate', department: 'Electronics and Telecommunication Engineering', year: '2017', educationType: 'M.Tech', achievement: ' MTech IIT Bombay', photo: 'images/Shreekanya Kodate.png' },
    { name: 'Sandeep Sharma', department: 'Electronics and Telecommunication Engineering', year: '2008', educationType: 'MS', achievement: 'MS  Missouri University of science and technology', photo: 'images/Sandeep Sharma.png' },
    { name: 'Nilkanth Kadlag', department: 'Electronics and Telecommunication Engineering', year: '2023', educationType: 'MBA', achievement: 'MS University of Georgia', photo: 'images/Nilkanth Kadlag.png' },

];
