const distinguishedAlumni = [
    { name: 'Dr. Ajay Verma', department: 'Computer Science and Engineering (AI-ML)', year: '2020', educationType: 'ME', achievement: 'PhD from MIT, AI Research Scientist at Google', photo: 'images/default-avatar.jpg' },
    { name: 'Ramesh Kumar', department: 'Computer Science and Engineering (AI-ML)', year: '2019', educationType: 'MBA', achievement: 'MBA from IIM Ahmedabad, Product Manager at Microsoft', photo: 'images/default-avatar.jpg' },
    { name: 'Satish Chandra', department: 'Computer Science and Engineering (AI-ML)', year: '2018', educationType: 'UPSC', achievement: 'IAS Officer, District Collector in Maharashtra', photo: 'images/default-avatar.jpg' },
    { name: 'Pradeep Singh', department: 'Computer Science and Engineering (AI-ML)', year: '2017', educationType: 'ME', achievement: 'MS from Stanford, Lead Engineer at Tesla', photo: 'images/default-avatar.jpg' },
    { name: 'Neeta Desai', department: 'Computer Science and Engineering (AI-ML)', year: '2016', educationType: 'MBA', achievement: 'MBA from Harvard, VP at Goldman Sachs', photo: 'images/default-avatar.jpg' },
    { name: 'Arun Joshi', department: 'Computer Science and Engineering (AI-ML)', year: '2015', educationType: 'MPSC', achievement: 'Maharashtra Administrative Service Officer', photo: 'images/default-avatar.jpg' },
    { name: 'Kavita Nair', department: 'Computer Science and Engineering (AI-ML)', year: '2021', educationType: 'ME', achievement: 'PhD from Oxford, Research Scientist at DeepMind', photo: 'images/default-avatar.jpg' },
    { name: 'Sunil Rao', department: 'Computer Science and Engineering (AI-ML)', year: '2019', educationType: 'MBA', achievement: 'MBA from Wharton, Entrepreneur Forbes 30 Under 30', photo: 'images/default-avatar.jpg' },
    { name: 'Vinay Kulkarni', department: 'Computer Science and Engineering (AI-ML)', year: '2018', educationType: 'UPSC', achievement: 'IPS Officer, Superintendent of Police', photo: 'images/default-avatar.jpg' },
    { name: 'Meera Patil', department: 'Computer Science and Engineering (AI-ML)', year: '2020', educationType: 'ME', achievement: 'MS from Carnegie Mellon, Senior Architect at Amazon', photo: 'images/default-avatar.jpg' },
    { name: 'Rajiv Sharma', department: 'Computer Science and Engineering (AI-ML)', year: '2017', educationType: 'MBA', achievement: 'MBA from ISB Hyderabad, Startup Founder', photo: 'images/default-avatar.jpg' },
    { name: 'Anita Reddy', department: 'Computer Science and Engineering (AI-ML)', year: '2019', educationType: 'MPSC', achievement: 'Deputy Collector, Revenue Department', photo: 'images/default-avatar.jpg' },
    { name: 'Kiran Malhotra', department: 'Computer Science and Engineering (AI-ML)', year: '2016', educationType: 'ME', achievement: 'PhD from Berkeley, Professor at IIT Bombay', photo: 'images/default-avatar.jpg' },
    { name: 'Sanjay Gupta', department: 'Computer Science and Engineering (AI-ML)', year: '2018', educationType: 'MBA', achievement: 'MBA from XLRI, Director at Deloitte', photo: 'images/default-avatar.jpg' },
    { name: 'Pooja Iyer', department: 'Computer Science and Engineering (AI-ML)', year: '2020', educationType: 'UPSC', achievement: 'IRS Officer, Assistant Commissioner', photo: 'images/default-avatar.jpg' },
    { name: 'Vikram Bhat', department: 'Computer Science and Engineering (AI-ML)', year: '2017', educationType: 'ME', achievement: 'MS from ETH Zurich, Principal Engineer at Google', photo: 'images/default-avatar.jpg' },
    { name: 'Sunita Menon', department: 'Computer Science and Engineering (AI-ML)', year: '2019', educationType: 'MBA', achievement: 'MBA from INSEAD, Strategy Consultant at McKinsey', photo: 'images/default-avatar.jpg' },
    { name: 'Ashok Pillai', department: 'Computer Science and Engineering (AI-ML)', year: '2018', educationType: 'MPSC', achievement: 'Sales Tax Officer, Commercial Taxes Department', photo: 'images/default-avatar.jpg' },
    { name: 'Lakshmi Nair', department: 'Computer Science and Engineering (AI-ML)', year: '2021', educationType: 'ME', achievement: 'PhD from Cambridge, AI Research Lead at Meta', photo: 'images/default-avatar.jpg' },
    { name: 'Ravi Krishnan', department: 'Computer Science and Engineering (AI-ML)', year: '2016', educationType: 'MBA', achievement: 'MBA from LBS London, Investment Banker at Morgan Stanley', photo: 'images/default-avatar.jpg' },

    { name: 'Prof. Sunita Reddy', department: 'Computer Engineering REGIONAL', year: '2019', educationType: 'ME', achievement: 'Professor at IIT Bombay, Published 50+ Research Papers', photo: 'images/default-avatar.jpg' },
    { name: 'Mahesh Tiwari', department: 'Computer Engineering REGIONAL', year: '2018', educationType: 'MBA', achievement: 'MBA from FMS Delhi, CEO of Tech Startup', photo: 'images/default-avatar.jpg' },
    { name: 'Rekha Agarwal', department: 'Computer Engineering REGIONAL', year: '2020', educationType: 'UPSC', achievement: 'IAS Officer, Secretary to Government', photo: 'images/default-avatar.jpg' },
    { name: 'Praveen Mishra', department: 'Computer Engineering REGIONAL', year: '2017', educationType: 'ME', achievement: 'PhD from Toronto, Data Scientist at IBM', photo: 'images/default-avatar.jpg' },
    { name: 'Sapna Chopra', department: 'Computer Engineering REGIONAL', year: '2019', educationType: 'MBA', achievement: 'MBA from SPJIMR, Marketing Head at Unilever', photo: 'images/default-avatar.jpg' },
    { name: 'Amit Saxena', department: 'Computer Engineering REGIONAL', year: '2016', educationType: 'MPSC', achievement: 'Assistant Commissioner, Public Works Department', photo: 'images/default-avatar.jpg' },
    { name: 'Divya Sinha', department: 'Computer Engineering REGIONAL', year: '2021', educationType: 'ME', achievement: 'MS from Georgia Tech, Software Engineer at Apple', photo: 'images/default-avatar.jpg' },
    { name: 'Nitin Pandey', department: 'Computer Engineering REGIONAL', year: '2018', educationType: 'MBA', achievement: 'MBA from MDI Gurgaon, Business Analyst at BCG', photo: 'images/default-avatar.jpg' },
    { name: 'Swati Bhatt', department: 'Computer Engineering REGIONAL', year: '2019', educationType: 'UPSC', achievement: 'IPS Officer, Deputy Commissioner of Police', photo: 'images/default-avatar.jpg' },
    { name: 'Alok Jain', department: 'Computer Engineering REGIONAL', year: '2020', educationType: 'ME', achievement: 'MS from Cornell, Research Engineer at NVIDIA', photo: 'images/default-avatar.jpg' },
    { name: 'Rita Yadav', department: 'Computer Engineering REGIONAL', year: '2017', educationType: 'MBA', achievement: 'MBA from IIM Calcutta, Senior Manager at Amazon', photo: 'images/default-avatar.jpg' },
    { name: 'Manoj Dubey', department: 'Computer Engineering REGIONAL', year: '2019', educationType: 'MPSC', achievement: 'Revenue Officer, Land Records Department', photo: 'images/default-avatar.jpg' },
    { name: 'Seema Sharma', department: 'Computer Engineering REGIONAL', year: '2016', educationType: 'ME', achievement: 'PhD from NUS Singapore, Assistant Professor at IIT Delhi', photo: 'images/default-avatar.jpg' },
    { name: 'Varun Gupta', department: 'Computer Engineering REGIONAL', year: '2018', educationType: 'MBA', achievement: 'MBA from IMT Ghaziabad, Operations Manager at Flipkart', photo: 'images/default-avatar.jpg' },
    { name: 'Nandini Thakur', department: 'Computer Engineering REGIONAL', year: '2020', educationType: 'UPSC', achievement: 'IFS Officer, Deputy Secretary in MEA', photo: 'images/default-avatar.jpg' },
    { name: 'Harish Singh', department: 'Computer Engineering REGIONAL', year: '2017', educationType: 'ME', achievement: 'MS from Waterloo, Machine Learning Engineer at Uber', photo: 'images/default-avatar.jpg' },
    { name: 'Anjali Menon', department: 'Computer Engineering REGIONAL', year: '2019', educationType: 'MBA', achievement: 'MBA from IIM Bangalore, Product Manager at Google', photo: 'images/default-avatar.jpg' },
    { name: 'Ranjan Kulkarni', department: 'Computer Engineering REGIONAL', year: '2018', educationType: 'MPSC', achievement: 'Sub-Divisional Officer, General Administration', photo: 'images/default-avatar.jpg' },
    { name: 'Priyanka Bhat', department: 'Computer Engineering REGIONAL', year: '2021', educationType: 'ME', achievement: 'PhD from Imperial College, Research Scientist at Intel', photo: 'images/default-avatar.jpg' },
    { name: 'Sanjay Pillai', department: 'Computer Engineering REGIONAL', year: '2016', educationType: 'MBA', achievement: 'MBA from NMIMS, Finance Manager at JP Morgan', photo: 'images/default-avatar.jpg' },

    { name: 'Mr. Karan Malhotra', department: 'Information Technology (IT)', year: '2018', educationType: 'MBA', achievement: 'CEO of Tech Startup, Forbes 30 Under 30', photo: 'images/default-avatar.jpg' },
    { name: 'Dr. Suresh More', department: 'Information Technology (IT)', year: '2019', educationType: 'ME', achievement: 'PhD from UCLA, Senior Scientist at Qualcomm', photo: 'images/default-avatar.jpg' },
    { name: 'Rajesh Pawar', department: 'Information Technology (IT)', year: '2020', educationType: 'UPSC', achievement: 'IES Officer, Executive Engineer in BSNL', photo: 'images/default-avatar.jpg' },
    { name: 'Anuja Kadam', department: 'Information Technology (IT)', year: '2017', educationType: 'MBA', achievement: 'MBA from IIM Lucknow, HR Director at TCS', photo: 'images/default-avatar.jpg' },
    { name: 'Pravin Jadhav', department: 'Information Technology (IT)', year: '2019', educationType: 'ME', achievement: 'MS from UT Austin, Security Architect at Cisco', photo: 'images/default-avatar.jpg' },
    { name: 'Vaishali Gaikwad', department: 'Information Technology (IT)', year: '2016', educationType: 'MPSC', achievement: 'Police Sub-Inspector, State CID', photo: 'images/default-avatar.jpg' },
    { name: 'Sameer Bhosale', department: 'Information Technology (IT)', year: '2021', educationType: 'ME', achievement: 'MS from USC, Software Developer at Netflix', photo: 'images/default-avatar.jpg' },
    { name: 'Rupali Shinde', department: 'Information Technology (IT)', year: '2018', educationType: 'MBA', achievement: 'MBA from IIM Indore, Brand Manager at Procter & Gamble', photo: 'images/default-avatar.jpg' },
    { name: 'Nikhil Nikam', department: 'Information Technology (IT)', year: '2019', educationType: 'UPSC', achievement: 'IRS Officer, Income Tax Inspector', photo: 'images/default-avatar.jpg' },
    { name: 'Jyoti Mohite', department: 'Information Technology (IT)', year: '2020', educationType: 'ME', achievement: 'PhD from TU Munich, Researcher at Siemens', photo: 'images/default-avatar.jpg' },
    { name: 'Akash Sawant', department: 'Information Technology (IT)', year: '2017', educationType: 'MBA', achievement: 'MBA from Great Lakes, Consultant at PwC', photo: 'images/default-avatar.jpg' },
    { name: 'Shraddha Kale', department: 'Information Technology (IT)', year: '2019', educationType: 'MPSC', achievement: 'Assistant Engineer, Maharashtra PWD', photo: 'images/default-avatar.jpg' },
    { name: 'Omkar Rathod', department: 'Information Technology (IT)', year: '2016', educationType: 'ME', achievement: 'MS from Columbia, DevOps Lead at Adobe', photo: 'images/default-avatar.jpg' },
    { name: 'Sayali Mane', department: 'Information Technology (IT)', year: '2018', educationType: 'MBA', achievement: 'MBA from Symbiosis, Supply Chain Manager at Mahindra', photo: 'images/default-avatar.jpg' },
    { name: 'Mayur Chavan', department: 'Information Technology (IT)', year: '2020', educationType: 'UPSC', achievement: 'IRTS Officer, Indian Railway Traffic Service', photo: 'images/default-avatar.jpg' },
    { name: 'Tejaswini Patil', department: 'Information Technology (IT)', year: '2017', educationType: 'ME', achievement: 'MS from Purdue, Cloud Engineer at Oracle', photo: 'images/default-avatar.jpg' },
    { name: 'Sagar Desai', department: 'Information Technology (IT)', year: '2019', educationType: 'MBA', achievement: 'MBA from IIM Kozhikode, Investment Analyst at KPMG', photo: 'images/default-avatar.jpg' },
    { name: 'Priyanka Bhalerao', department: 'Information Technology (IT)', year: '2018', educationType: 'MPSC', achievement: 'Tehsildar, Revenue Administration', photo: 'images/default-avatar.jpg' },
    { name: 'Tushar Jagtap', department: 'Information Technology (IT)', year: '2021', educationType: 'ME', achievement: 'PhD from EPFL, Research Associate at IBM Research', photo: 'images/default-avatar.jpg' },
    { name: 'Rashmi Kulkarni', department: 'Information Technology (IT)', year: '2016', educationType: 'MBA', achievement: 'MBA from XIMB, Sales Head at Salesforce', photo: 'images/default-avatar.jpg' },

    { name: 'Dr. Neha Gupta', department: 'Computer Engineering', year: '2019', educationType: 'ME', achievement: 'Lead Architect at Microsoft Azure', photo: 'images/default-avatar.jpg' },
    { name: 'Sanket Gore', department: 'Computer Engineering', year: '2018', educationType: 'MBA', achievement: 'MBA from IIM Ahmedabad, CFO at Startup', photo: 'images/default-avatar.jpg' },
    { name: 'Ashwini Kamble', department: 'Computer Engineering', year: '2020', educationType: 'UPSC', achievement: 'IAS Officer, Joint Secretary', photo: 'images/default-avatar.jpg' },
    { name: 'Yogesh Parab', department: 'Computer Engineering', year: '2017', educationType: 'ME', achievement: 'MS from UC Berkeley, Principal Engineer at LinkedIn', photo: 'images/default-avatar.jpg' },
    { name: 'Pallavi Shirke', department: 'Computer Engineering', year: '2019', educationType: 'MBA', achievement: 'MBA from IIM Bangalore, Strategy Manager at Accenture', photo: 'images/default-avatar.jpg' },
    { name: 'Ganesh Dhage', department: 'Computer Engineering', year: '2016', educationType: 'MPSC', achievement: 'Excise Inspector, State Excise Department', photo: 'images/default-avatar.jpg' },
    { name: 'Supriya Wagh', department: 'Computer Engineering', year: '2021', educationType: 'ME', achievement: 'MS from UIUC, Backend Engineer at Facebook', photo: 'images/default-avatar.jpg' },
    { name: 'Aniket Bhoir', department: 'Computer Engineering', year: '2018', educationType: 'MBA', achievement: 'MBA from FMS Delhi, Product Lead at Swiggy', photo: 'images/default-avatar.jpg' },
    { name: 'Madhuri Lad', department: 'Computer Engineering', year: '2019', educationType: 'UPSC', achievement: 'IFS Officer, Under Secretary in Finance Ministry', photo: 'images/default-avatar.jpg' },
    { name: 'Vishal Salunke', department: 'Computer Engineering', year: '2020', educationType: 'ME', achievement: 'PhD from University of Melbourne, Lecturer at IIT Madras', photo: 'images/default-avatar.jpg' },
    { name: 'Puja Ghorpade', department: 'Computer Engineering', year: '2017', educationType: 'MBA', achievement: 'MBA from ISB Hyderabad, Marketing Director at Nestle', photo: 'images/default-avatar.jpg' },
    { name: 'Sumit Sawant', department: 'Computer Engineering', year: '2019', educationType: 'MPSC', achievement: 'District Supply Officer, Supply Department', photo: 'images/default-avatar.jpg' },
    { name: 'Varsha Tandale', department: 'Computer Engineering', year: '2016', educationType: 'ME', achievement: 'MS from NYU, UX Designer at Airbnb', photo: 'images/default-avatar.jpg' },
    { name: 'Ajinkya Kharat', department: 'Computer Engineering', year: '2018', educationType: 'MBA', achievement: 'MBA from XLRI, Corporate Trainer at Infosys', photo: 'images/default-avatar.jpg' },
    { name: 'Shubhangi Ghule', department: 'Computer Engineering', year: '2020', educationType: 'UPSC', achievement: 'IES Officer, Assistant Engineer in Railways', photo: 'images/default-avatar.jpg' },
    { name: 'Nitin Mhatre', department: 'Computer Engineering', year: '2017', educationType: 'ME', achievement: 'MS from University of Washington, Cloud Architect at VMware', photo: 'images/default-avatar.jpg' },
    { name: 'Sarika Londhe', department: 'Computer Engineering', year: '2019', educationType: 'MBA', achievement: 'MBA from NMIMS, Business Analyst at EY', photo: 'images/default-avatar.jpg' },
    { name: 'Chetan Pawar', department: 'Computer Engineering', year: '2018', educationType: 'MPSC', achievement: 'Forest Officer, Forest Department', photo: 'images/default-avatar.jpg' },
    { name: 'Manali Raut', department: 'Computer Engineering', year: '2021', educationType: 'ME', achievement: 'PhD from KTH Sweden, Postdoc at ETH Zurich', photo: 'images/default-avatar.jpg' },
    { name: 'Rohit Dhaigude', department: 'Computer Engineering', year: '2016', educationType: 'MBA', achievement: 'MBA from IIM Indore, Operations Head at Uber', photo: 'images/default-avatar.jpg' },

    { name: 'Eng. Rajesh Iyer', department: 'Mechanical Engineering', year: '2020', educationType: 'ME', achievement: 'Chief Engineer at Tesla Motors', photo: 'images/default-avatar.jpg' },
    { name: 'Santosh Kumbhar', department: 'Mechanical Engineering', year: '2018', educationType: 'MBA', achievement: 'MBA from IIM Calcutta, Plant Manager at Tata Motors', photo: 'images/default-avatar.jpg' },
    { name: 'Smita Bhosle', department: 'Mechanical Engineering', year: '2019', educationType: 'UPSC', achievement: 'IRSME Officer, Mechanical Engineer in Indian Railways', photo: 'images/default-avatar.jpg' },
    { name: 'Mahesh Kanade', department: 'Mechanical Engineering', year: '2017', educationType: 'ME', achievement: 'MS from University of Michigan, Design Engineer at Ford', photo: 'images/default-avatar.jpg' },
    { name: 'Anuja Patil', department: 'Mechanical Engineering', year: '2019', educationType: 'MBA', achievement: 'MBA from NITIE Mumbai, Logistics Manager at Maersk', photo: 'images/default-avatar.jpg' },
    { name: 'Dattatray Shinde', department: 'Mechanical Engineering', year: '2016', educationType: 'MPSC', achievement: 'Executive Engineer, Irrigation Department', photo: 'images/default-avatar.jpg' },
    { name: 'Renuka Jadhav', department: 'Mechanical Engineering', year: '2021', educationType: 'ME', achievement: 'MS from RWTH Aachen, Automotive Engineer at BMW', photo: 'images/default-avatar.jpg' },
    { name: 'Avinash Gawde', department: 'Mechanical Engineering', year: '2018', educationType: 'MBA', achievement: 'MBA from SP Jain, Project Manager at Larsen & Toubro', photo: 'images/default-avatar.jpg' },
    { name: 'Vidya Koli', department: 'Mechanical Engineering', year: '2019', educationType: 'UPSC', achievement: 'IES Officer, Joint Director in CPWD', photo: 'images/default-avatar.jpg' },
    { name: 'Ramesh Patil', department: 'Mechanical Engineering', year: '2020', educationType: 'ME', achievement: 'PhD from TU Delft, Aerospace Engineer at Airbus', photo: 'images/default-avatar.jpg' },
    { name: 'Lata Sutar', department: 'Mechanical Engineering', year: '2017', educationType: 'MBA', achievement: 'MBA from TAPMI, Quality Manager at Bosch', photo: 'images/default-avatar.jpg' },
    { name: 'Sharad Bhagat', department: 'Mechanical Engineering', year: '2019', educationType: 'MPSC', achievement: 'Deputy Engineer, Public Works Department', photo: 'images/default-avatar.jpg' },
    { name: 'Sunita Mane', department: 'Mechanical Engineering', year: '2016', educationType: 'ME', achievement: 'MS from Virginia Tech, Manufacturing Engineer at General Electric', photo: 'images/default-avatar.jpg' },
    { name: 'Balaji Rane', department: 'Mechanical Engineering', year: '2018', educationType: 'MBA', achievement: 'MBA from IIM Lucknow, Supply Chain Analyst at Cummins', photo: 'images/default-avatar.jpg' },
    { name: 'Ujwala Salve', department: 'Mechanical Engineering', year: '2020', educationType: 'UPSC', achievement: 'IRSEE Officer, Electrical Engineer in Railways', photo: 'images/default-avatar.jpg' },
    { name: 'Dnyaneshwar Bhosale', department: 'Mechanical Engineering', year: '2017', educationType: 'ME', achievement: 'MS from Georgia Tech, Robotics Engineer at Boston Dynamics', photo: 'images/default-avatar.jpg' },
    { name: 'Kavita Pawar', department: 'Mechanical Engineering', year: '2019', educationType: 'MBA', achievement: 'MBA from IIM Kozhikode, Operations Manager at Mahindra', photo: 'images/default-avatar.jpg' },
    { name: 'Sunil Gaikwad', department: 'Mechanical Engineering', year: '2018', educationType: 'MPSC', achievement: 'Assistant Commissioner, Urban Development', photo: 'images/default-avatar.jpg' },
    { name: 'Nanda Shinde', department: 'Mechanical Engineering', year: '2021', educationType: 'ME', achievement: 'PhD from Caltech, Research Engineer at SpaceX', photo: 'images/default-avatar.jpg' },
    { name: 'Prakash Todkar', department: 'Mechanical Engineering', year: '2016', educationType: 'MBA', achievement: 'MBA from MDI Gurgaon, Business Development Manager at Siemens', photo: 'images/default-avatar.jpg' },

    { name: 'Ar. Pooja Deshmukh', department: 'Civil Engineering', year: '2021', educationType: 'ME', achievement: 'Award-winning Architect, National Design Prize', photo: 'images/default-avatar.jpg' },
    { name: 'Rahul Bhagwat', department: 'Civil Engineering', year: '2018', educationType: 'MBA', achievement: 'MBA from IIM Bangalore, Infrastructure Consultant at Deloitte', photo: 'images/default-avatar.jpg' },
    { name: 'Aparna Kulkarni', department: 'Civil Engineering', year: '2019', educationType: 'UPSC', achievement: 'IRSE Officer, Senior Section Engineer in Railways', photo: 'images/default-avatar.jpg' },
    { name: 'Sanjay Thorat', department: 'Civil Engineering', year: '2017', educationType: 'ME', achievement: 'MS from UC Davis, Structural Engineer at Arup', photo: 'images/default-avatar.jpg' },
    { name: 'Manisha Pawar', department: 'Civil Engineering', year: '2019', educationType: 'MBA', achievement: 'MBA from IIM Indore, Project Manager at Shapoorji Pallonji', photo: 'images/default-avatar.jpg' },
    { name: 'Deepak Jagtap', department: 'Civil Engineering', year: '2016', educationType: 'MPSC', achievement: 'Assistant Engineer, Maharashtra Jeevan Pradhikaran', photo: 'images/default-avatar.jpg' },
    { name: 'Seema Desai', department: 'Civil Engineering', year: '2021', educationType: 'ME', achievement: 'MS from TU Berlin, Urban Planner at UN-Habitat', photo: 'images/default-avatar.jpg' },
    { name: 'Pandurang More', department: 'Civil Engineering', year: '2018', educationType: 'MBA', achievement: 'MBA from SCMHRD, Contracts Manager at DLF', photo: 'images/default-avatar.jpg' },
    { name: 'Pushpa Kadam', department: 'Civil Engineering', year: '2019', educationType: 'UPSC', achievement: 'IES Officer, Superintending Engineer in CPWD', photo: 'images/default-avatar.jpg' },
    { name: 'Vijay Shinde', department: 'Civil Engineering', year: '2020', educationType: 'ME', achievement: 'PhD from NUS, Assistant Professor at IIT Kharagpur', photo: 'images/default-avatar.jpg' },
    { name: 'Asha Bhosale', department: 'Civil Engineering', year: '2017', educationType: 'MBA', achievement: 'MBA from IIM Ahmedabad, Real Estate Manager at Godrej Properties', photo: 'images/default-avatar.jpg' },
    { name: 'Mohan Kamble', department: 'Civil Engineering', year: '2019', educationType: 'MPSC', achievement: 'Executive Engineer, Water Resources Department', photo: 'images/default-avatar.jpg' },
    { name: 'Shobha Raut', department: 'Civil Engineering', year: '2016', educationType: 'ME', achievement: 'MS from Imperial College, Environmental Engineer at Bechtel', photo: 'images/default-avatar.jpg' },
    { name: 'Baban Patil', department: 'Civil Engineering', year: '2018', educationType: 'MBA', achievement: 'MBA from NITIE, SCM Manager at ACC Cement', photo: 'images/default-avatar.jpg' },
    { name: 'Vandana Gore', department: 'Civil Engineering', year: '2020', educationType: 'UPSC', achievement: 'IRSME Officer, Deputy Chief Mechanical Engineer', photo: 'images/default-avatar.jpg' },
    { name: 'Ashok Jadhav', department: 'Civil Engineering', year: '2017', educationType: 'ME', achievement: 'MS from Texas A&M, Geotechnical Engineer at Jacobs', photo: 'images/default-avatar.jpg' },
    { name: 'Sudha Sawant', department: 'Civil Engineering', year: '2019', educationType: 'MBA', achievement: 'MBA from IIM Lucknow, Business Analyst at CBRE', photo: 'images/default-avatar.jpg' },
    { name: 'Dhananjay Parab', department: 'Civil Engineering', year: '2018', educationType: 'MPSC', achievement: 'Deputy Collector, General Administration Department', photo: 'images/default-avatar.jpg' },
    { name: 'Leela Mane', department: 'Civil Engineering', year: '2021', educationType: 'ME', achievement: 'PhD from TU Delft, Transportation Engineer at AECOM', photo: 'images/default-avatar.jpg' },
    { name: 'Chandrakant Nikam', department: 'Civil Engineering', year: '2016', educationType: 'MBA', achievement: 'MBA from Great Lakes, Project Director at Tata Projects', photo: 'images/default-avatar.jpg' }
];
